### ISSUE TITLE
for all notification email, ensure that "from" is correct

### ISSUE THREAD

**Issue by lperson** [RagtagOpen/nomad#108]
This is how it is now: **from@example.com via mailgun.org**

**Comment by iandees** [comment]
I just changed it to "nomad@ragtag.org". I don't think that actually exists, but it's better than "from@example.com".

**Comment by engerm** [comment]
@bradyk @jillh510 thoughts on what the from/return email address should be?

If we use nomad@ragtag.org could someone create that. And if so should the email be forwarded to a support account?

I just want to ensure that a user doesn't hit reply and get a bounce back or no reply

**Comment by lperson** [comment]
@iandees regarding your comment [above](https://github.com/RagtagOpen/nomad/issues/108#issuecomment-333281950), did you make the change on mailgun?

**Comment by engerm** [comment]
Currently it's set to "nomad@ragtag.org".

I replied to it and got a bounce. 

We need to figure a solution.

@bradyk @jillh510 Thoughts?

We could create a nomad@ragtag.org account should a user reply to an email and then forward those emails to either some of us supporting Nomad.  

An alternate solution is for the reply to address be linked to Intercom account

**Comment by iandees** [comment]
The from address is changed using the `MAIL_DEFAULT_SENDER` environment variable.

**Comment by jillh510** [comment]
I think the correct email is 'nomad-help@ragtag.org'

**Comment by iandees** [comment]
This is configured properly in staging and production, so closing here.

**Comment by engerm** [comment]
waiting for Email to be fixed.
