### ISSUE TITLE
Extraneous screen between "join carpool" and actually joining

### ISSUE THREAD

**Issue by maiamcc** [RagtagOpen/nomad#116]
<img width="639" alt="screen shot 2017-09-17 at 10 12 25 pm" src="https://user-images.githubusercontent.com/6332648/30653009-e423f786-9df7-11e7-8bc7-342227af4d03.png">

<img width="640" alt="screen shot 2017-09-17 at 10 12 35 pm" src="https://user-images.githubusercontent.com/6332648/30653019-e735cbd4-9df7-11e7-9286-0ebae591ae25.png">

Either a. screen 2 should not exist, clicking the button in screen 1 should directly register you to the carpool (in conjunction with #106, should be obvious to the user that they've request to join the carpool) or b. screen 2 should contain more useful info (e.g. summary of the ride details) and a button with different copy, like maybe “confirm” or “yes, request a spot in this carpool”.

**Comment by maiamcc** [comment]
@schloo @dluetger larry mentioned that the wireframing things you’re doing will maybe mitigate this issue (useless interstitial page when joining carpools) — is that the case? if so, can one of you assign this issue to yourself so that we know that it’s being handled?

**Comment by schloo** [comment]
new ui takes care of this!
