### ISSUE TITLE
set up alerting for critical errors on data dog or some other free service

### ISSUE THREAD

**Issue by lperson** [RagtagOpen/nomad#118]
Current motivation: fail to send email.  That requires human intervention to make sure riders make other arrangements.

User story: Caleb signed up for a carpool.  The carpool was cancelled.  Caleb was not notified.  Caleb showed up at the advertised place at the advertised time.  Caleb was sad and frustrated.  Caleb walked into a bar and had too much to drink, instead of going to the canvassing event.  Caleb developed dehydration and alcohol poisoning and needed to be hospitalized.  Caleb had no health insurance because he did not renew his ACA policy.  Caleb also did not renew his DACA registration.  Caleb was deported.  Let's find a way to notify Caleb so this doesn't happen.

**Comment by maiamcc** [comment]
😭

**Comment by lperson** [comment]
Maybe use century?

**Comment by iandees** [comment]
Events are going to Sentry here: https://sentry.io/ragtag/carpools-staging/

DM me on Slack with your email and I will invite you to this team.
