### ISSUE TITLE
webui: /profile - permissions error

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#135]
get an error 500 loading https://ragtag-carpool.herokuapp.com/profile as an authenticated user

Steps:

1. Login as a user (maybe with admin privs)

2. load https://ragtag-carpool.herokuapp.com/profile

**Comment by iandees** [comment]
This was fixed in staging and I forgot to push to production. Just did that now.

**Comment by engerm** [comment]
Get error:

```
Forbidden

You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.
```

**Comment by iandees** [comment]
This sounds like a transient problem with logins or cookies. Are you able to reproduce it? There's no code that would produce a "Forbidden" on the `/profile` endpoint.

**Comment by engerm** [comment]
No longer an issue.

Closing.
