### ISSUE TITLE
security vulnerabilty: webui - site vulnerable to clickjacking

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#137]
The site is vulnerable to clickjacking.

Steps:

1. Create file: 

```
<html>
<iframe src=https://ragtag-carpool.herokuapp.com/></iframe>
</html>
```

2. Load file

Note that heroku site loads in iframe making it vulnerable to clickjacking/CSS redress

**Comment by iandees** [comment]
This is fixed in production. (Using an `X-Frame-Options` header)
