### ISSUE TITLE
webui: should not be able to create a user with a blank name

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#138]
Currently the is a user with no name. All Names should be required in order to create a user.

Step.

Log in as admin

load: https://ragtag-carpool.herokuapp.com/admin/users

**Comment by iandees** [comment]
When a user is first logs in, we point them to the profile page and ask them to fill in their profile. The profile form won't let you save your profile with a blank name, but it's possible to skip the page and never hit save on the profile after logging in.

I'm thinking we let people putz around the website after logging in with a blank name but if they try to create a carpool or join a carpool as a rider, they must have a complete profile. Where "complete profile" is at least name, gender, email.

**Comment by engerm** [comment]
@iandees , can this be closed?

**Comment by iandees** [comment]
Yea, I think so. We check for profile completeness before allowing carpool creation or rider signup. If that doesn't work then it's a new/different bug.
