### ISSUE TITLE
webui: internal server error when adding a destination with invalid address

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#139]
Get an internal server error when creating a Destination with a malformed Address

Steps:

log into webui

load: https://ragtag-carpool.herokuapp.com/admin/destinations/new

set address to:

> sdfsdf234234-----"

**Comment by iandees** [comment]
https://sentry.io/ragtag/carpools/issues/356614543/

**Comment by iandees** [comment]
This is fixed in production.
