### ISSUE TITLE
webui: server error 500 after logging in with google

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#140]
After logging in with google oauth, there is a 500 error in nomad

<img width="1082" alt="screen shot 2017-09-27 at 5 16 58 pm" src="https://user-images.githubusercontent.com/17053096/30938384-d8cf9ac4-a3a7-11e7-913c-d01fd2871625.png">

Steps:

1. load https://ragtag-carpool.herokuapp.com

2. Login in with google oauth (tested with an admin account)

Upon being redirected back to nomad get an error 500 with the following URL:

```
https://ragtag-carpool.herokuapp.com/callback/google?code=4%2Fo1Ed01riAOk8qAvvlhNvjJ2lMuVSs0gf93HNgXAjPkU#
```

**Comment by iandees** [comment]
https://sentry.io/ragtag/carpools/issues/356736571/
