### ISSUE TITLE
webui: invalid phone number get internal server error (server side)

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#146]
Server response provides internal server error when signing up with an invalid password; there is client side validation but there is no graceful server side validation

Steps:

1. Login

2. Sign up using an invalid phone number buy bypassing client side validation.

**Comment by iandees** [comment]
Is this different than https://github.com/RagtagOpen/nomad/issues/136?

**Comment by iandees** [comment]
Please re-open or create a new issue if it's different.
