### ISSUE TITLE
webui: /carpools/find XSS vulnerability from gender

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#151]
XSS from gender https://ragtag-carpool.herokuapp.com/carpools/find

steps:

1. signup as a driver

2. create a ride

3. specify gender as:

```
female"><img src=x onerror=alert(/gender/)>-
```

4. save

5. now search for valid rides

<img width="1209" alt="screen shot 2017-09-28 at 9 14 40 am" src="https://user-images.githubusercontent.com/17053096/30975157-8686c34e-a43f-11e7-8b82-7f4080268cb0.png">

**Comment by iandees** [comment]
This is fixed in production.

**Comment by engerm** [comment]
Tested and verified fixed
