### ISSUE TITLE
webui: /carpools/find XSS vulnerability from seat

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#152]
XSS from gender https://ragtag-carpool.herokuapp.com/carpools/find

steps:

1. signup as a driver

2. create a ride

3. specify seats as:

```
4"><img src=x onerror=alert(/seat/)>-
```

4. save

5. now search for valid rides

<img width="1209" alt="screen shot 2017-09-28 at 9 14 47 am" src="https://user-images.githubusercontent.com/17053096/30975249-d44536f6-a43f-11e7-910e-a1b0031cd5af.png">

**Comment by iandees** [comment]
This is fixed in production.

**Comment by engerm** [comment]
Verified.
