### ISSUE TITLE
webui: /carpools/find does not show available seat left

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#154]
/carpools/find shows capacity but does not update when a user requests a ride; should also show available seats

There need to be something tracking the awaiting approval ride state to show how many seats are left

**Comment by iandees** [comment]
The "Capacity" column shows "seats available" on the carpool. Seats available is calculated based on the `number of seats - number of confirmed riders`. It won't update after you request a seat, it will only update after the driver has confirmed that you're riding.

**Comment by engerm** [comment]
Ok.

Removed priority.

Not sure this is an issue then, unless we think it should be an enhancement. 

Thoughts @iandees

**Comment by iandees** [comment]
Closing it. This is also very close to #204.
