### ISSUE TITLE
webui: all server response errors should have Nomad template

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#158]
Steps:

load https://ragtag-carpool.herokuapp.com/lsdjfsjdf

**Comment by schloo** [comment]
i have the 403/404/500 templates up, but maybe theyre not hooked in yet

**Comment by iandees** [comment]
Done in #261.

**Comment by engerm** [comment]
Seems like all are wrapped in template now. If new ones are discovered then create a new issue to address that error page
