### ISSUE TITLE
webui - make destination updatable; fix destination deleting

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#159]
Currently on destinations can be CRD (create, read, delete).

Destinations should support updating/editing.

Destination can be hidden but the information cannot be changed with deleting the destination and recreating it. Not sure that would be a good flow if all ride information is lost.

**Comment by lperson** [comment]
Also fixed some bugs with deleting destinations.

**Comment by engerm** [comment]
Destinations are now CRU-able.

Delete is not working. Will create a new issue to track this
