### ISSUE TITLE
webui on heroku - slow performance

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#164]
Slow performance from webui on heroku

**Comment by iandees** [comment]
I need more to go off of than that...

What's slow? When? What're you doing that's slow?

**Comment by engerm** [comment]
pages are occasionally loading slow taking about 5-10 seconds

**Comment by iandees** [comment]
Which pages?

**Comment by engerm** [comment]
Happened on /admin and another page. It's not happening now. Issue does not seem to be consistent

**Comment by engerm** [comment]
Has not happened recently.

Closing the issue. Will reopen if experiencing again
