### ISSUE TITLE
webui: any user can see old/canceled rides

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#169]
Any user has the ability to previous, old, or canceled rides

This poses a possible information disclosure to a threat actor by showing all rides and providing a general list of activity to a campaign

Users should only see current carpools and not be able to retrieve old or cancelled carpools.

Steps

log in as a normal user.

Load the following link to see all carpools:
https://ragtag-carpool.herokuapp.com/carpools/find

Start cycling through: carpools
https://ragtag-carpool.herokuapp.com/carpools/1
https://ragtag-carpool.herokuapp.com/carpools/2
https://ragtag-carpool.herokuapp.com/carpools/3
https://ragtag-carpool.herokuapp.com/carpools/4
https://ragtag-carpool.herokuapp.com/carpools/5
https://ragtag-carpool.herokuapp.com/carpools/6
...

**Comment by iandees** [comment]
Does switching to UUIDs for IDs help with this?

Canceled carpools are deleted from the database, so they will 404. (See also #199)
Carpools that weren't canceled and have happened will stick around but not be discoverable in search.

**Comment by engerm** [comment]
@iandees unable to verify it it's still an issue.

The cancel carpool button doesnt work.

I will create a separate issue to address this

**Comment by jillh510** [comment]
Cancelling carpool seems to work now; can this be tested and closed?

**Comment by iandees** [comment]
Going to close this.

**Comment by engerm** [comment]
This is fixed tested;

Get a 404 now.

Canceled:
https://nomad-staging.ragtag.org/carpools/cee8a7ed-0273-4268-8a1b-10a5075e6491


Old: still able to see. Since this is not a priority issue, I will just create a new issue to address old rides:
https://nomad-staging.ragtag.org/carpools/52beea1e-357d-4bca-80ef-21c210b6c020
