### ISSUE TITLE
No indication that I'm in a carpool

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#17]
Steps to reproduce:
- As a passenger, signed up for a carpool
- (got approved by the driver)
- As a passenger, went to the "Find a Carpool" page
Result: there's no indication on my carpool that I've been accepted. If I click on the carpool, it allows me to cancel my seat request, but there's no indication that I've been accepted.

Expected: The "Find a Carpool" page should show which carpools I've requested and which I've been accepted to. The Carpool page should show whether my request is accepted or still awaiting the driver's response.

**Comment by lperson** [comment]
I went ahead and mitigated this, even though it was tagged enhancement, because it was driving me nuts, doing so gave me some hands-on with the code, and it also facilitates testing email, which will depend on the state of the request.

**Comment by engerm** [comment]
@lperson can this be closed?
