### ISSUE TITLE
create nomad-dev.ragtag.org

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#171]
As handoff and deployment nears, nomad.ragtag.org will be used for production. 

There will need to be a test site for development purposes. This is a request to get nomad-dev.ragtag.org running for ragtag volunteers to test and develop nomad without interfering with the production site.

**Comment by engerm** [comment]
@iandees I believe we can close this.

**Comment by iandees** [comment]
Yup I agree.

**Comment by iandees** [comment]
We've got a staging and prod instance. If we want more than that let's figure out what they should do.

**Comment by engerm** [comment]
sure, i'll remove priority for now since staging is up
