### ISSUE TITLE
web server information disclosure: nomad.ragtag.org

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#175]
The server is disclosure the service and version.

Update server settings to not include service name and version

```
HTTP/1.1 200 OK
Connection: close
Server: gunicorn/19.7.1
Date: Sat, 30 Sep 2017 03:32:20 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 2284
X-Frame-Options: DENY
Strict-Transport-Security: max-age=31536000
Via: 1.1 vegur
```

**Comment by iandees** [comment]
Doesn't look like Heroku has a way to remove the `Server` or `Via` headers (at least in 2015) https://stackoverflow.com/a/34242192

**Comment by iandees** [comment]
Closing this as there isn't anything we can do here.

**Comment by engerm** [comment]
Confirming.

We met Friday 10/13 and accepted the risk.
