### ISSUE TITLE
webui: "Other..." destinations should be added to the main destinations list in Admin

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#178]
Currently when an "Other..." destination is added from /carpools/new it is not added to the /admin/destinations list. This /admin/destinations list should list all destinations, including ones the admin(s) did not create.

Steps:

1. Log in as user.
2. Create a new carpool
3. For "Going to" click "Other..."
4. Fill in new address
5. Click Add Your Ride
6. Log in as an admin
7. Load /admin/destinations

Note the recently created destination is not listed

**Comment by iandees** [comment]
The "Destinations" admin page lists the "canned destinations", not general destinations. This is probably not a bug and probably should go through a UX or design discussion before we spend much time on it.

**Comment by engerm** [comment]
OK.

**Comment by iandees** [comment]
We're getting rid of the concept of "other" destinations, so I'm closing this.
