### ISSUE TITLE
Carpool creation page is lacking fields

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#18]
Please see https://docs.google.com/document/d/1sD8OQDsuap_mthChrkcXIAfno-YcE2saQ-q5KP_Ow-g/edit

**Comment by iandees** [comment]
Which fields are missing?

**Comment by jillh510** [comment]
From the doc:

Say smoking/non-smoking
Give other info about the car (allergens? Space in the trunk for suitcases?)

**Comment by iandees** [comment]
I'm going to close this for now. The create carpool page has a "note" field that can cover this stuff.
