### ISSUE TITLE
https://nomad-staging.ragtag.org/ application error

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#181]
The staging server is down:
<img width="724" alt="screen shot 2017-09-30 at 1 01 49 am" src="https://user-images.githubusercontent.com/17053096/31042658-f4a30112-a57a-11e7-88cd-0ee7f7977e82.png">

**Comment by iandees** [comment]
I was trying to let it go to sleep so we didn't pay $7/mo for staging, but clearly didn't do it right. Fixed now.
