### ISSUE TITLE
webui: no validation of email field on user profile page

### ISSUE THREAD

**Issue by mjlepouttre** [RagtagOpen/nomad#192]
Steps to reproduce:

* login as a user via Google
* update your email address to some invalid type such as user@domain.com.com
* click "Update Your Profile"

Actual result: changes are saved and success notification is displayed

Expected result: error validation is displayed for invalid email address

**Comment by iandees** [comment]
The email field has slightly better validation now.

I'm going to co-opt this ticket to bring up what to do when a user attempts to change their email, though:

1. Should we allow a user to change their email? When we pull in an email from Google or Facebook it's almost always previously verified deliverable. If they change it, that might no longer be the case.
1. If we allow the user to change their email, should we require them to click a link in the email to confirm the new email address? If we allow this, we're already pretty close to having our own email/account system and we might as well support logging in without a Google or Facebook account, too.

**Comment by dryan** [comment]
We're covering this more thoroughly in #186. Closing it out in favor of that one.
