### ISSUE TITLE
mobile webui: iphone /carpools/new not using geolocation

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#193]
The /carpools/new is not using geolocation to limit events in the mobile user's area.

A mobile device should list carpools in there area, not 500+ miles away.

![img_1222](https://user-images.githubusercontent.com/17053096/31047643-485fe8d6-a5dc-11e7-85d5-22fb2b556502.PNG)

**Comment by iandees** [comment]
This is fixed in #287.

**Comment by engerm** [comment]
No works on iPhone.

iPhone
* The "Create a Ride" page show the map area where the user is.
* The "Find a Ride" page doesn't show the map on the find page


Mac using Chrome
* The "Create a Ride" page show the map area where the user is.
* The "Find a Ride" page doesn't show the map on the find page
