### ISSUE TITLE
mobile web ui: confusing gender requirement messages on profile page

### ISSUE THREAD

**Issue by simonl2002** [RagtagOpen/nomad#194]
**Description**
When submitting a profile update with no gender there's confusing messaging There's a green notification saying "You updated your profile" and there's also a message saying "Please specify your gender before creating a carpool request." Gender appears to be required but the validation does not work like field such as "phone" which is outlined in red when there's a validation issue.

**Steps**
Prereq: A signed in user
1. navigate to /profile
2. Do NOT enter gender
3. Submit the form

**Actual Results**
Two messages appears above form. One saying profile updated, the other saying gender is required. Additionally the gender validation error is in blue which does not really indicate something bad.

**Expected Results**
Gender field should be highlighted in red and form shouldn't submit. 
![screenshot_20170930-122621](https://user-images.githubusercontent.com/284357/31047653-71158010-a5dc-11e7-9423-d96ada36d861.png)

**Comment by iandees** [comment]
This should be fixed with the new profile design and some changes to the profile form's validation stuff.

**Comment by engerm** [comment]
Working now.
