### ISSUE TITLE
webui: on /carpools/new, manually editing the year in the depart/return fields w/ an invalid value crashes the page

### ISSUE THREAD

**Issue by mjlepouttre** [RagtagOpen/nomad#197]
Browsers: Chrome 61, Firefox 55

Steps to reproduce: 

* navigate to https://nomad.ragtag.org/carpools/new
* click in the depart/return input field to display the datepicker
* select a date
* in the input field, manually edit the year to some invalid value like 1017

Actual result: the page crashes

Expected result: the year gets reset to current year (this is the current behavior for an invalid month or day value)

**Comment by iandees** [comment]
The date picker and validation should prevent this from happening now.
