### ISSUE TITLE
CSRF: Request to "cancel your seat request" request is GET. Should be POST

### ISSUE THREAD

**Issue by simonl2002** [RagtagOpen/nomad#198]
When cancelling a carpool request a GET request is issued to url like: https://nomad.ragtag.org/carpools/28/request/18/cancel

Given that this is changing data on the backend the request should be a POST

**Comment by engerm** [comment]
@simonl2002 there is a two (2) step process for cancelling a carpool

1) click the "Cancel your carpool" button. This redirects to a page asking why it's being cancelled; no data is changed on the backend.
2) click "Cancel your ride". This request is a POST request.

Can this issue be closed?

**Comment by simonl2002** [comment]
@engerm maybe this has changed in the intervening time? Definitely wasn't seeing an extra screen when rider went to cancel. I can double check this.

**Comment by engerm** [comment]
@simonl2002 any update?

**Comment by simonl2002** [comment]
Yeah this is still valid. `cancel your seat request` is a GET. I think I probably caused confusion above when I said "cancel your ride"

**Comment by engerm** [comment]
@simonl2002 is correct, cancel your seat in a carpool is a GET

This page is vulnerable to CSRF:


Sample GET request:

```
GET /carpools/8f6c5fc5-8b53-43c9-8620-11a6b4297ba8/request/4ef6b969-a90f-47af-97fd-205c5d216702/cancel HTTP/1.1
Host: nomad.ragtag.org
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: https://nomad.ragtag.org/carpools/8f6c5fc5-8b53-43c9-8620-11a6b4297ba8
Cookie: session=.eJwdj0FuQyEMRK9Ssc7CGGMgl4nAHqtVpVb6P1lFuXto9_PmzTzTLQ6cn-l6Px64pNuXp2siAHlGjBrBNDxz7wpxj8zcnTuNPOoQsE7y4lbmTnVqXIxRCkSYfVSbk5rmEKpF-8rSbZHX2VomJWkROYhXYKENNkOfGzNJl2TnEbf77zd-9h4bmLui-qZb0zFoO7jUKtTrAi3nuaC6uceJ4__EM308_q4U5YYm28OStz8yAkZY7gq19Hq9AZvWSdA.DLnHIQ.BWBBwJLL9Lx69O2g0n9bcsostL0; remember_token=03627e74-f022-418c-bf1e-fec0ebdd6e6c|98172265deaf71f9415c394346b4ecf6018d84a6c6a9da8afde8da7148aa9a9952c74484f43bdb47e5b2850fcd68048c1c924a2bef4fd9888770f0ab743a6583
DNT: 1
Connection: close
Upgrade-Insecure-Requests: 1

```

**Comment by iandees** [comment]
#374 should have fixed this.

**Comment by engerm** [comment]
No CSRF.

GET are not allowed and POST check the csrf_token
