### ISSUE TITLE
Allow passengers to see only carpools that are in the right area

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#2]
Use case: Passenger comes to the app and wants to find a carpool leaving from a convenient location.

One option is to display departure places on a map, let the potential passenger pan and zoom, and only list those carpools that appear in the view (like how Yelp does it).

**Comment by iandees** [comment]
With the latest change to add a location search on the "find a ride" page, the results are ordered by distance from the location entered. It'll still show rides that are hundreds of miles away from the location the user typed, which is probably not desired.

A couple ideas for next steps:
1. (Jill's idea above) Only show pools in the bounds of the map view
1. Add a distance dropdown "5, 10, 50 miles from ..." and then limit the search to only include results in that radius.

**Comment by engerm** [comment]
Per @iandees's comment, the results are sorted by distance.

Looks good but future releases should allow to sort by distance, date, and/or location
