### ISSUE TITLE
/carpools/find table layout needs adjusting on Android

### ISSUE THREAD

**Issue by mjlepouttre** [RagtagOpen/nomad#205]
![screenshot_20170930-140218](https://user-images.githubusercontent.com/1630603/31048288-3d3ca7e4-a5e8-11e7-82d9-a01a85d7af19.png)

Phone: Google Nexus 5X
OS: Android 7.1.2
Browser: Chrome 61

Table layout on /carpools/find could use some adjustment, need to scroll sideways to see all of the info.

**Comment by jillh510** [comment]
Page has been rearranged; closing as obsolete.
