### ISSUE TITLE
webui: get an error 500 when changing someone to an admin

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#207]
<img width="724" alt="screen shot 2017-09-30 at 2 22 20 pm" src="https://user-images.githubusercontent.com/17053096/31048434-e2ba6b6e-a5ea-11e7-8855-20fbb51287ec.png">

When granting someone admin rights, there is Error 500 message.

Steps

Log in as a user1
Log in as an admin
Grant user1 admin rights

Get an Error 500.

Expected results:

There would be no Error 500

**Comment by iandees** [comment]
This is an error in the template rendering so the admin toggle is still working it's just failing to redirect you properly.

**Comment by simonl2002** [comment]
This also occurs when you remove admin privileges from a user.

**Comment by iandees** [comment]
https://sentry.io/ragtag/carpools/issues/358563278/
