### ISSUE TITLE
webui: cookies need be secure and HTTP only

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#209]
Cookies are not secure and HTTP only.

Server settings should be changed to have secure and HTTP only cookies.

![screen shot 2017-09-30 at 2 49 20 pm 2](https://user-images.githubusercontent.com/17053096/31048713-2334c7ce-a5f1-11e7-8974-e8367b531390.png)

**Comment by iandees** [comment]
Do you mean https-only? What's an http-only cookie?

**Comment by engerm** [comment]
The "Secure" flag and the "HTTP Only" flags should be set
