### ISSUE TITLE
email templates aren't including all addresses

### ISSUE THREAD

**Issue by mjlepouttre** [RagtagOpen/nomad#211]
The following emails don't contain addresses for a carpool:

When a rider requests a seat:

> We wanted to let you know that Maurice Lepouttre has requested a ride with you in the car leaving from at 2017-12-31 15:30:00+00:00.

When a driver approves a request:

> Good news! Maurice Lepouttre approved your request to join the carpool from to 400 Broad Street, Seattle, WA, United States, departing at 2017-12-31 15:30:00+00:00.

When a driver denies a request:

> Unfortunately, the driver declined your request to join the carpool from to 1370 Park Place Northwest, Washington D.C., DC 20010, United States, departing at 2017-10-01 15:50:00+00:00.

When a driver cancels a carpool:

> Unfortunately, the carpool session for leaving from 1701 5th Avenue, New York, NY, United States at 2017-12-31 15:30:00+00:00 has been cancelled.

**Comment by flynnwastaken** [comment]
#439

**Comment by dryan** [comment]
These were fixed by #439
