### ISSUE TITLE
webui: "Manage your rides" should be a button

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#212]
Similar to "Look for a ride" blue button, the "Manage your rides" link should also be a button

<img width="1366" alt="screen shot 2017-09-30 at 3 46 04 pm" src="https://user-images.githubusercontent.com/17053096/31048918-a31a31e0-a5f6-11e7-9da0-a17cfe6ffafc.png">

**Comment by iandees** [comment]
This is purposefully different because it's more likely that people are coming to look for a ride than offer one, so I wanted to draw attention to that first.

The wireframes probably have something to say about this, too?

**Comment by schloo** [comment]
they do! right now we are actually leading with searching for a ride as the main CTA on the home page, with a smaller link to create a ride if you can drive. there's no "manage my rides" button in the body of the page; instead it's accessible through the header only (if the user is logged in).

![image](https://user-images.githubusercontent.com/2453862/31056513-d1f80190-a6a0-11e7-8715-4ff02229a767.png)
