### ISSUE TITLE
Name field isn't properly populated on signup with Facebook

### ISSUE THREAD

**Issue by simonl2002** [RagtagOpen/nomad#214]
**Description**

When signing up via Facebook the name field is not properly populated with my full name. Instead it seems use the user portion of my email address. 

**Steps**

1. Signup via Facebook

**Actual Results**
Name shows up as "simonl2002" which is not my name on Facebook.

![screenshot_20170930-161804](https://user-images.githubusercontent.com/284357/31049183-d27dc6c2-a5fb-11e7-931a-73367e8b2718.png)

**Expected Results**
Name field should be populated with name from Facebook.

**Comment by flynnwastaken** [comment]
I got this too

**Comment by iandees** [comment]
It might be because we aren't asking for permission to get your name.

**Comment by simonl2002** [comment]
@iandees I think name is one of the things that you can't control permissions for. Everything has access.

**Comment by iandees** [comment]
Fixed in https://github.com/RagtagOpen/nomad/pull/285/commits/44c53d341169afbb8374515a0b98aed14bd52104.
