### ISSUE TITLE
webui: notification after signing up for ride

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#227]
After signing up for a ride the user gets a "You've been added to the list for this carpool!".

It might be informative to inform the user they are on a wait list awaiting approval.

<img width="653" alt="screen shot 2017-10-03 at 7 27 30 pm" src="https://user-images.githubusercontent.com/17053096/31153783-0198b102-a871-11e7-9a97-b22665db7eeb.png">

**Comment by jillh510** [comment]
Add to alert: "You'll get an email when you are approved."

**Comment by AaronSofaer** [comment]
Picture in OP is out of date; copy has changed in the meantime. Added the string you mention to the new copy, Jill.
