### ISSUE TITLE
web template - get mobile template for new interface

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#230]
the new interface needs a mobile template

**Comment by schloo** [comment]
pushed these, but i'm having trouble logging in and getting the pages to work, so they need to be QA'ed on mobile

**Comment by schloo** [comment]
Have a giant UI update pull request for the responsive site, it's been deployed here until someone merges it. https://ragtag-carpool-pr-252.herokuapp.com

**Comment by iandees** [comment]
This was fixed in #252.

**Comment by engerm** [comment]
New interface exists and looks great.

Any updates will be tracked in new individual issues.
