### ISSUE TITLE
on first signin - the profile page's default value

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#231]
On first login the profile page should either:

- default to the values pulled from the oauth

or

- should be all blank.

![screen shot 2017-10-07 at 11 09 12 am](https://user-images.githubusercontent.com/17053096/31309175-ff37fc56-ab4f-11e7-9c26-da1655d31661.png)

**Comment by iandees** [comment]
This was fixed in #257.

**Comment by mjlepouttre** [comment]
@iandees I just created a new gmail account and logged into Nomad with it, and the name, gender, and phone number fields did not get populated:

![screenshot from 2017-10-09 20-39-09](https://user-images.githubusercontent.com/1630603/31364325-f943c832-ad31-11e7-9720-3dc181a57778.png)

**Comment by iandees** [comment]
Yep, you get sent to the profile page to fill in the details that we can't pull from the Google or Facebook account.

If we didn't get a name from Google then you probably didn't set it in your Gmail account.

**Comment by jillh510** [comment]
Or you have a G-suite account on a different domain, in which case the API in its wisdom doesn't retrieve your name.

**Comment by engerm** [comment]
Tested. Pulls name in
