### ISSUE TITLE
unable to update Profile

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#233]
As authenticated user is unable to update their profile information

**Comment by iandees** [comment]
Pretty sure this is the same as #231. Nothing is updating because the values in the profile page are fake from the template.

**Comment by jillh510** [comment]
If the user does "save changes", the app makes this call: http://localhost:5000/profile?user-name=Punky+Brewster&user-name=&user-email=spunky%40gmail.com&user-phone=212-555-5555&checkbox-email=email
which doesn't seem to save to the db.

**Comment by jillh510** [comment]
(in other words, the values entered in the form are sent to the server, but the db isn't updated)

**Comment by iandees** [comment]
Yep, that's the same as #231. The profile page is just not wired up to the backend.
