### ISSUE TITLE
template: /profile not scaling properly

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#235]
The /profile "Edit your profile" page is no scaling correctly.

Content seems to be half the width of the page. 

<img width="1265" alt="screen shot 2017-10-07 at 1 01 45 pm" src="https://user-images.githubusercontent.com/17053096/31310100-f6310bd8-ab5f-11e7-8a8f-a3c655ebe0b0.png">

**Comment by schloo** [comment]
fixed
