### ISSUE TITLE
template: /login not scaling properly

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#236]
The /login "Log in to continue" page is no scaling correctly.

Content seems to be half the width of the page. 

![screen shot 2017-10-07 at 1 10 41 pm](https://user-images.githubusercontent.com/17053096/31310162-1718c61e-ab61-11e7-9057-401080d86ae7.png)

**Comment by engerm** [comment]
related t0 #235

**Comment by schloo** [comment]
this is intentional to optimize line length for readability
