### ISSUE TITLE
web template: the Ride drop-down doesn't fit the text

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#237]
The text in the "Find/Give a ride" appears to be too wide for the dropdown itself.

The dropdown should be wider.

<img width="1552" alt="screen shot 2017-10-07 at 1 17 37 pm" src="https://user-images.githubusercontent.com/17053096/31310268-013c70a0-ab63-11e7-91ba-c875c42f753f.png">

**Comment by schloo** [comment]
@engerm which browser is this? couldnt reproduce it

**Comment by iandees** [comment]
I've noticed stuff like this when the browser has old CSS cached. Try a hard refresh?
