### ISSUE TITLE
template: main page not scaling properly

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#238]
The main page page is no scaling correctly.

Content seems to be half the width of the page. The header also does not seem to be scaling.

May be related to #235 and #236 

<img width="1267" alt="screen shot 2017-10-07 at 1 29 48 pm" src="https://user-images.githubusercontent.com/17053096/31310318-f87373dc-ab63-11e7-96e4-655539d3ec1d.png">

**Comment by schloo** [comment]
this however, is NOT intentional... 😛

**Comment by schloo** [comment]
fixed
