### ISSUE TITLE
Add content to Privacy page

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#244]
@bradyk is crafting content for the privacy page, in regards to how user data will be used and shared with the campaign.

https://nomad-staging.ragtag.org/privacy.html

**Comment by schloo** [comment]
Added these pages. Privacy Policy page is accessible through the main header, TOU is available through a link in the footer of the index page.

**Comment by engerm** [comment]
Closing. The header link is called "Privacy & Terms". The content has been added to it.

<img width="1498" alt="screen shot 2017-10-12 at 6 01 17 am" src="https://user-images.githubusercontent.com/17053096/31490682-c79a1d08-af12-11e7-9149-6a278b747a81.png">
