### ISSUE TITLE
send reminder email to driver and riders for safety tips

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#245]
Drivers and riders should be send reminders for safety tips

**Comment by jillh510** [comment]
Can we add the safety tips in existing emails (including the one that arrives two days before they leave) rather than adding additional emails?

**Comment by engerm** [comment]
Yes, the safety tip message can be incorporated into another email that is sent.

We should leave this bug open to verify the driver and passenger(s) get an email at some point that includes the safety tips.
