### ISSUE TITLE
Find page shows a lot of information before search

### ISSUE THREAD

**Issue by cgeisser** [RagtagOpen/nomad#249]
https://nomad.ragtag.org/carpools/find shows a lot of information before a search is entered. This allows a malicious to learn a lot about campaign tactics, headcount, etc.

Suggestions:
- require a search to be entered before showing results
- limit search to a small number of the closest results.
- hide as much information as possible until a user is logged in
- If there's nothing within X miles, prompt the user to start a carpool rather than expanding the search

Most of these changes will need to be made on the https://nomad.ragtag.org/carpools/starts.geojson api endpoint

**Comment by jillh510** [comment]
Obligate the user to allow location or enter a search term. And yes, make the change at the API level, not the UI level.

**Comment by iandees** [comment]
Does #661 close this?
