### ISSUE TITLE
Limit rides per user

### ISSUE THREAD

**Issue by cgeisser** [RagtagOpen/nomad#255]
Each user should only be allowed to have a small number of future rides they are signed up to give or go on. Basic abuse prevention.

**Comment by btoron** [comment]
Should we also add some "ride incompatibility" check? i.e. if the user has requested (and it is accepted) a ride from day A to day B then the user can't request a ride starting on day C (A<B<C)

**Comment by jillh510** [comment]
Prevent a non-admin user from having > 10 rides booked at any given time. If the suggestion to look for people who want to be in two carpools at the same time proves easy to implement, go for it. But not a priority.

Admin users can book as many rides as they like.

**Comment by tkell** [comment]
Working on this one!

**Comment by AaronSofaer** [comment]
@jillh510 what's the desired response behavior if you try to sign up for an eleventh ride?

**Comment by jillh510** [comment]
Instead of going to the carpools page (/carpools/76212cfe-d455-4bc8-a6dd-158247a52999 or similar), go to a new page that says "Sorry, you can be in at most ten carpools. Please try again after some of your carpools have finished."

**Comment by jillh510** [comment]
Reopening to confirm that this is max 10 carpools, meaning combination of carpools in which the user is either a driver or a passenger.

**Comment by kielni** [comment]
it's only looking at ride requests now; will update tonight
