### ISSUE TITLE
Need to add space for error messages in form

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#258]
C
![screen shot 2017-10-07 at 9 11 41 pm](https://user-images.githubusercontent.com/2319837/31313844-298a31e6-aba4-11e7-8bfd-f4a5b7934afa.png)
urly braces before "Edit your profile" text.

**Comment by iandees** [comment]
The ugly braces are how I'm showing form error messages right now.

@schloo, can you give an example of what an error message attached to a form element would look like?

**Comment by schloo** [comment]
Just created some styles for it:

![image](https://user-images.githubusercontent.com/2453862/31314401-f75b1efe-abcd-11e7-8ae1-e7700fe28ed9.png)

**Comment by schloo** [comment]
An HTML format sample is in the Profile template:

https://github.com/RagtagOpen/nomad/pull/252/commits/9c10c2102abfbd6657e7ffa4e631fa5ed47f110f#diff-28e52e6c1e81a428a767f2fb297f5b19

**Comment by iandees** [comment]
@schloo this will work, but I was thinking of a style that highlighted the form element that had the problem and then gave a bit of space in the text to describe the problem.

**Comment by iandees** [comment]
I did this for now:

![image](https://user-images.githubusercontent.com/261584/31322481-c5ebb348-ac5d-11e7-82dc-9e950690e36e.png)

**Comment by schloo** [comment]
FYI, making these all these all `label`s instead of `p`s
