### ISSUE TITLE
"Prefer to self-describe" option for gender needs text

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#259]
"Prefer to self-describe" option on the Profile screen should have a text box where the user can put their definition.

**Comment by iandees** [comment]
It does:

![image](https://user-images.githubusercontent.com/261584/31313851-3ef6cb14-abb5-11e7-8e4f-7c4276b32209.png)

**Comment by iandees** [comment]
(Woah that's a big screenshot)

**Comment by jillh510** [comment]
Ooh, clever, it only shows up when you choose "self-describe"!
