### ISSUE TITLE
on first login into profile, get {} at top of page

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#262]
After a new user signs in and is redirected to /profile (Profile page) there is a /{}/ at the top of the page.

There shouldn't be a /{}/ there. Not sure what it is.

![screen shot 2017-10-08 at 7 51 01 am](https://user-images.githubusercontent.com/17053096/31316535-71ae0444-abfd-11e7-882c-8ef70947f66a.png)

**Comment by schloo** [comment]
this is related to #258 . that's ian's placeholder for error messages, i've provided the UI styles in that thread for him to use
