### ISSUE TITLE
/carpools/new - able to create ride that starts before it ends

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#264]
A driver can create a carpool that starts before the ending date/time.

There needs to be client-side validation and server-side validation to ensure an end date/time is after the start date/time.

![screen shot 2017-10-08 at 8 04 20 am](https://user-images.githubusercontent.com/17053096/31316645-62b61fba-abff-11e7-96ee-4046737780af.png)

**Comment by iandees** [comment]
Fixed in #282.
