### ISSUE TITLE
/carpools/find - devices should detect location

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#266]
When a user loads the "Find rides near you" page should detect location, such as when using a smart phone, to zoom into an X mile radius of that location.

![img_1270](https://user-images.githubusercontent.com/17053096/31316750-be5fa122-ac01-11e7-8fe4-271fa6d7ce23.PNG)
![img_1271](https://user-images.githubusercontent.com/17053096/31316751-c2df6e58-ac01-11e7-933e-ba44302201ce.PNG)

**Comment by kielni** [comment]
fixed by https://github.com/RagtagOpen/nomad/pull/287
