### ISSUE TITLE
/carpools/find - map should zoom when user searches for a carpool

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#267]
When a user searches, or when a browser detects a location such as when using a smart phone, the "Find rides near you" should zoom into an X mile radius of that location.

https://nomad-staging.ragtag.org/carpools/find?lat=&lon=&q=20002

<img width="1546" alt="screen shot 2017-10-08 at 8 15 11 am" src="https://user-images.githubusercontent.com/17053096/31316755-e7709274-ac01-11e7-96f5-dd536f0d2060.png">

**Comment by iandees** [comment]
Closed in #287.
