### ISSUE TITLE
A field for general location that is displayable for searching

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#268]
This has been part of a discussion where we have told users to pick a public location to meet at and that Nomad would display a "general location", not the exact address, except to the riders a couple days before the carpool's departure.

The current form fields ask and display the exact address in the web browser, but to use a general location.

The current needs a field that will be a "displayable" general location. A user would enter something like "K and 14". No specific address should be shared at this point.

Another option would be to start the address in the geolocation and shift it a bit that is somewhat randomized or broadened.

* /carpools/new
* /carpools/find

REQUEST: add a label for drivers to change the display label. Change from hidden input to text input.

<img width="1546" alt="screen shot 2017-10-08 at 8 26 11 am" src="https://user-images.githubusercontent.com/17053096/31316951-01f0ce4e-ac06-11e7-9579-d40aa4104a74.png">

**Comment by jillh510** [comment]
Can this issue be dup'ed to #327 ?

**Comment by engerm** [comment]
No. #327 is tracking the pull; this issue (#268) is tracking the issue. 

We will want someone to verify the issue is fixed once it has been closed and merged.

**Comment by iandees** [comment]
I updated the form to make the description/name of the departure spot editable by the user. When they move the pin on the map it will reverse geocode an address to include there by default, but they can also change it to be something more generic like so:

![image](https://user-images.githubusercontent.com/261584/31571604-b3635a44-b05b-11e7-81f1-1f8048691fd5.png)

**Comment by iandees** [comment]
This is used as the departure name and looks like this on the carpools/find map listing:

![image](https://user-images.githubusercontent.com/261584/31571618-03ecb3b6-b05c-11e7-9550-fb72a65e6593.png)

**Comment by engerm** [comment]
Seems to be working good for me
