### ISSUE TITLE
copywriting pass of Nomad

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#269]
This is tracking the review of all words in Nomad pages to ensure they are in the right place and spelling and grammar are correct.

**Comment by engerm** [comment]
I checked the main page

**Comment by flynnwastaken** [comment]
Checked Give a Ride

**Comment by flynnwastaken** [comment]
Checked Privacy & Terms

**Comment by flynnwastaken** [comment]
Checked My Rides
