### ISSUE TITLE
/carpools/new - unable to use the calendar selector in FF and Safari

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#271]
On the /carpools/new page (Start a new carpool - Provide carpool details), a user can use the calendar dropdown menu to select a date. In firefox this is not working; the ability to use that calendar is not there. The calendar works in chrome.

Tested on macos using FF 55.0.3

<img width="1546" alt="screen shot 2017-10-08 at 12 04 58 pm" src="https://user-images.githubusercontent.com/17053096/31318451-0f1887b8-ac21-11e7-930a-ee8e3090a239.png">

**Comment by iandees** [comment]
Looks like Firefox 56 doesn't support the native date picker that most other browsers do.

https://caniuse.com/#feat=input-datetime

Firefox 57 will support it, though.

**Comment by engerm** [comment]
Could we get some some text added to those inputs with an example of an accepted date or something like  'MM/DD/yy'?

**Comment by engerm** [comment]
The calendar widget is also NOT working in Safari

**Comment by jillh510** [comment]
Needs UI design first.

**Comment by jillh510** [comment]
Or perhaps just doing this: https://www.jqueryscript.net/time-clock/Cross-browser-Date-Time-Selector-For-jQuery-dateTimePicker.html, which seems like it'll look the same across browsers.

**Comment by jayallen** [comment]
@jillh510 Is Nomad already using jQuery?  It doesn't look like it on first inspection.  That's seems to me to be sort of a heavy requirement for a single widget, no?

**Comment by jayallen** [comment]
Oops, nevermind.  It looks like it is: https://github.com/RagtagOpen/nomad/blob/master/app/templates/_template.html

**Comment by jayallen** [comment]
I just pushed a fix for this in #593, using the jQuery plugin that @jillh510 suggested.  It works on Safari 11.1.2 and of course Firefox 61.0.1 and Chrome 67.0.3396.99.  Given that I don't have FF 55 and because this is my first commit to Nomad, it should absolutely be reviewed and tested by the original reporter.

**Comment by jillh510** [comment]
So can this be closed?

**Comment by jayallen** [comment]
Well, It's been merged into the master branch but I'd like @engerm to verify.

**Comment by dryan** [comment]
Using browserstack.com I tested on Firefox 55 and Safari 10.1. Neither have a widget present. That said FF 56 is where support begins and it's 6 versions back. I also doubt we get that much desktop Safari usage. I vote to close this out.
