### ISSUE TITLE
unable to cancel a carpool

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#272]
The buttons on the "Are you sure you want to cancel this carpool?"

The "Nevermind, go back" and the "Cancel" buttons are not working.

A driver should be able to cancel their ride/carpool.

A driver should also be able to change their mind and not cancel their ride/carpool.

![screen shot 2017-10-08 at 12 22 53 pm](https://user-images.githubusercontent.com/17053096/31318650-c14cf8c2-ac23-11e7-9908-b232ea0c6c30.png)

**Comment by iandees** [comment]
Fixed in #278.
