### ISSUE TITLE
/profile - the phone number error doesn't seem right...

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#275]
When entering an invalid phone number the error message doesn't seem right

![screen shot 2017-10-08 at 2 22 58 pm](https://user-images.githubusercontent.com/17053096/31319596-589ad46e-ac34-11e7-9e5b-4c6207f7e096.png)

**Comment by iandees** [comment]
The error message looks like this now:

![image](https://user-images.githubusercontent.com/261584/31322496-3f4dcdfc-ac5e-11e7-8328-ea4a1f5befdf.png)
