### ISSUE TITLE
Feature: email reminders

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#291]
This is the feature request to send out a reminder email a day or 2 in advance of the departure of the carpool to the drivers and riders.

The drivers' emails should contain:
- Contact information about all passengers - Name, gender, contact information (email, phone), and additional notes.
- Departure information - location and date/time
- Return departure information - location and date/time
- Campaign information - Address of campaign location/meeting area and contact information for the campaign
- Link to privacy page
- The safety tips (link to page and the content itself)

The riders' emails should contain:
- Contact information about the diver - Name, gender, contact information (email, phone), and additional notes.
- Departure information - location and date/time
- Return departure information - location and date/time
- Campaign information - Address of campaign location/meeting area and contact information for the campaign
- Link to privacy page
- The safety tips (link to page and the content itself)

---

After bringing this up on the 10/8 sync-up call, @iandees said it would require a background process to check for emails that need sent every hour. The background process could also handle sending other email notifications

**Comment by iandees** [comment]
The background process part of this was done in #392. Putting together the emails and scheduling them still needs to be done. Also, if you had something going for the background process (or some other way of doing it) already, @kielni, I'd love to see it.

**Comment by flynnwastaken** [comment]
I've written these email templates, once #439 is resolved and the HTML in the templates is working these can be scheduled

**Comment by flynnwastaken** [comment]
driver_reminder.html/.txt and rider_reminder.html/.txt in the templates folder. They need to be changed to pull rider(s) contact info and driver contact info respectively into the body of the email, as pointing to the carpool info page at this point contains no contact info

**Comment by flynnwastaken** [comment]
the ride_approved.html has driver email in it, but no other rider-directed email template does or has other contact info, and no driver directed template has rider contact info at all

**Comment by jkriss** [comment]
@iandees This is the issue for a cron job for sending ride reminders

**Comment by iandees** [comment]
With #458 merged, this "should be working". I didn't close it because I didn't have a chance to test it with an email happening, though.

**Comment by jillh510** [comment]
On Tuesday, set up a carpool that's supposed to leave at 2 pm on Friday. It's past 2 pm on Wednesday (both GMT and in my local timezone) and I (the driver) got no emails.

**Comment by jillh510** [comment]
woohoo! Got the driver email! Now just need to test the passenger email!

**Comment by jillh510** [comment]
Woohoo!
