### ISSUE TITLE
Need safety tips

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#292]
Need some general language with tips for safety- rides and drivers.

This content will be on a Nomad page (don't know which one right now) and included in the reminder email

**Comment by schloo** [comment]
Since the top nav tab is called "Privacy & Terms" instead of "Safety" now, I think it'd be cool to have this on the home page.

**Comment by jillh510** [comment]
Flynn will write the tips

**Comment by flynnwastaken** [comment]
SAFETY TIPS
    for rider:
Have a live phone conversation with your driver before the pickup
Check out your driver’s social media profile(s)
Make sure a friend or family member knows where you’re going and with who; check in with them at stages of your trip and canvassing
Charge your phone
    
    for driver
Have a live phone conversation with your passengers before the pickup
Check out your passengers’ social media profiles
Make sure a friend or family member knows where you’re going and with who; check in with them at stages of your trip and canvassing
Charge your phone

CANVASSING TIPS
Charge your phone
Get the volunteer coordinator’s phone number
Listen carefully to all instructions
If a house or encounter with a constituent makes you feel uncomfortable for any reason, retreat, move on, and alert the local volunteer coordinator
Bring water and a snack

**Comment by flynnwastaken** [comment]
I have put the rider's and canvassing language in the ride_approved.html / ride_approved.txt and I have put the driver's and canvassing language in the ride_requested.html / ride_requested.txt
