### ISSUE TITLE
success/error messages are displaying on next page load

### ISSUE THREAD

**Issue by mjlepouttre** [RagtagOpen/nomad#296]
As an example, sign up for a ride, then visit another page. You'll see the "You've been added to the list for this carpool" success message on that new page.

![screenshot from 2017-10-09 21-09-55](https://user-images.githubusercontent.com/1630603/31364955-38dab0b0-ad36-11e7-8eee-2555ed7f6c0a.png)

Here, I've navigated to the /carpools/new page right after signing up for a ride.

**Comment by iandees** [comment]
This is happening because some of the templates are missing the flashes (and /carpools/new does).

**Comment by dryan** [comment]
Why not just put the flashes in _template.html so they don't have to get added everywhere?

**Comment by iandees** [comment]
Cuz the _template.html page is used as a base for all the pages, and some of them would probably want different flash placements. I'm thinking mostly of the homepage, I suppose.

**Comment by AaronSofaer** [comment]
What's the desired outcome here that would close the ticket?

**Comment by jillh510** [comment]
I'm not seeing the original bug any more. Closing.
