### ISSUE TITLE
mobileui: header needs to be resized

### ISSUE THREAD

**Issue by mjlepouttre** [RagtagOpen/nomad#297]
On Android Chrome, I need to scroll way to the right to see the dropdown menu icon:

![screenshot_20171009-211428](https://user-images.githubusercontent.com/1630603/31365296-3ccc34da-ad38-11e7-81d4-e3218e70b901.png)

![screenshot_20171009-211436](https://user-images.githubusercontent.com/1630603/31365301-40dae986-ad38-11e7-8a20-8609ea98772e.png)

**Comment by jillh510** [comment]
Also an issue on "Find rides near you"
