### ISSUE TITLE
in header, change Privacy Policy to "Privacy & Terms"

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#305]
The now Privacy Policy page will include the privacy statement and the TOU.

**Comment by schloo** [comment]
added this yesterday, it's up on Staging. :) It's called Safety currently but I can change to Privacy & Terms if we prefer

**Comment by engerm** [comment]
@schloo thanks for making the change but it needs to have the word privacy in the link - Privacy & Terms

**Comment by schloo** [comment]
oops :) updated
