### ISSUE TITLE
Language change/Date format

### ISSUE THREAD

**Issue by flynnwastaken** [RagtagOpen/nomad#310]
![screen shot 2017-10-10 at 10 46 45 am](https://user-images.githubusercontent.com/32378726/31401826-e889b3d6-ada8-11e7-9c94-4f750f074ddc.png)
Should be changed from "Time" to "Date and Time", and/or made into a date selector rather than open field

**Comment by iandees** [comment]
The date text boxes are HTML5 date selectors. You should get a system date picker when you put your cursor in there.

**Comment by kielni** [comment]
<input type="date"> has limited browser support (Edge but not other IE, not Safari); what browser support requirements does Nomad have?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

**Comment by engerm** [comment]
https://github.com/RagtagOpen/nomad/issues/190

This was about changing "Depart Time" and "Return Time" to "Depart Date/Time" and "Return DateTime".

**Comment by jillh510** [comment]
To get things out the door, sufficient to change the labels to say "Departure Date (format YYYY-MM-DD)" and "Return Date (format YYYY-MM-DD)". Fancier solution can come later.

**Comment by dluetger** [comment]
So... any determination here as to whether the HTML5 selectors are sufficient? Also format has been changed to MM/DD/YYYY in another bug so if and when I change the label I'll make sure to make that the hint.

**Comment by jillh510** [comment]
HTML5 selectors, plus change the label on the input to indicate the correct format (for people using browsers that don't support the selector) is fine.

**Comment by dluetger** [comment]
Probably not a priority, but now the format in the label now duplicates the format suggestion from the placeholder text. Though I could see in this case the format in the label being more accessible.

**Comment by iandees** [comment]
The format placeholder doesn't show up in Firefox, which is what some folks seem to be testing with.
