### ISSUE TITLE
"Find a Ride" overlaps in header - Safari on Mac laptop

### ISSUE THREAD

**Issue by flynnwastaken** [RagtagOpen/nomad#312]
![screen shot 2017-10-10 at 10 57 54 am](https://user-images.githubusercontent.com/32378726/31402154-02f3bb26-adaa-11e7-9d18-106bc8170e76.png)
"Find a Ride" overlaps in header with location search box

**Comment by schloo** [comment]
to fix this i think we will have to do one or some of the following:
- dynamically set breakpoints with JS (probably not this)
- remove the search field from the header bar
- apply some truncation rules (e.g. "Flynn Ezr...")
