### ISSUE TITLE
Slight overlap on edges of My Carpools page - Safari on Mac

### ISSUE THREAD

**Issue by flynnwastaken** [RagtagOpen/nomad#313]
![screen shot 2017-10-10 at 11 02 50 am](https://user-images.githubusercontent.com/32378726/31402349-a0cf946e-adaa-11e7-88b0-12eb9bd700c1.png)
I can scroll a bit more to the right, but the left edge is cut off

**Comment by iandees** [comment]
Yea, this page could use some design help, @schloo. It hasn't been looked at since we put together the new design.

**Comment by schloo** [comment]
Definitely. This should be covered by #47 once it gets closed out

**Comment by schloo** [comment]
This got addressed in #47
