### ISSUE TITLE
self described gender not showing up in the "Driver's Corner: Passenger Requests"

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#319]
In the "Driver's Corner: Passenger Requests", the description for a passenger that chose to self-describe their gender is not showing up. It shows up that a passenger chose to self-describe, but it's not showing what the passenger entered.

Steps:

- As a rider/passenger, go to Profile

- Set gender as "Prefer to self-describe"

- Set the description to "test"

- Save changes

- Find a Ride. Sign up for ride

- Log in as driver. 

- Got to Driver's dashboard for that ride

- Look at incoming requests

[note no description of "test" for self-described gender]

- Allow rider

- Reload page

[note no description of "test" for self-described gender]

![screen shot 2017-10-11 at 7 57 00 am](https://user-images.githubusercontent.com/17053096/31439638-e39297fa-ae5a-11e7-9110-048e9f6ff3df.png)

**Comment by jmcarp** [comment]
Looks like this was resolved in https://github.com/RagtagOpen/nomad/commit/52fe76efe5bbc84ca818bb0bcd3ed16d5eab46c5. cc @iandees

**Comment by iandees** [comment]
Yep! Thanks.
