### ISSUE TITLE
CSRF: able to approve/deny riders in a carpool

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#320]
Able to CSRF a driver to approve/deny riders in their carpool.

The requests are GETs and should be a POST with the CSRF token

* https://nomad-staging.ragtag.org/carpools/babb71c9-f9e6-4297-a302-af775f91e254/request/f8018143-d85a-49ec-b926-08cf8c25298b/deny
* https://nomad-staging.ragtag.org/carpools/babb71c9-f9e6-4297-a302-af775f91e254/request/f8018143-d85a-49ec-b926-08cf8c25298b/approve

**Comment by jillh510** [comment]
Is this a duplicate of #321 ?

**Comment by engerm** [comment]
This one was a dupe or #321 

Github was having issues this day. 

Removing tags.
