### ISSUE TITLE
CSRF: able to approve/deny the passenger in a rider's carpool [use this]

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#321]
Able to CSRF a driver to approve/deny riders in their carpool.

The requests are GETs and should be a POST with the CSRF token

* https://nomad-staging.ragtag.org/carpools/babb71c9-f9e6-4297-a302-af775f91e254/request/f8018143-d85a-49ec-b926-08cf8c25298b/deny
* https://nomad-staging.ragtag.org/carpools/babb71c9-f9e6-4297-a302-af775f91e254/request/f8018143-d85a-49ec-b926-08cf8c25298b/approve

**Comment by jillh510** [comment]
https://github.com/RagtagOpen/nomad/tree/gets_to_posts is work in progress for this one.

**Comment by engerm** [comment]
Test and no longer vulnerable to CSRF

GET are not allowed and POST checks the csrf token
