### ISSUE TITLE
Mobile template: iOS scaling/width issue

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#322]
Scaling is not right on an iPhone.

**Comment by engerm** [comment]
![img_1280](https://user-images.githubusercontent.com/17053096/31471098-0bb6413c-aeb5-11e7-8d1b-2c9273224efb.PNG)

**Comment by dluetger** [comment]
@engerm Can you reproduce recently? It's looking okay on my device.

**Comment by engerm** [comment]
Still happening.

**Comment by engerm** [comment]
![img_1283](https://user-images.githubusercontent.com/17053096/31556354-b1c8093a-b012-11e7-8574-04c4ec113bdc.PNG)

**Comment by dryan** [comment]
This isn't happening on the current build on iOS 11 or iOS 12 beta.
