### ISSUE TITLE
Mobile: iOS button  cleanup

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#323]
The buttons on the login page should have the -or- between them. 

![img_1281](https://user-images.githubusercontent.com/17053096/31471212-b240f36c-aeb5-11e7-87df-a017869aa06e.PNG)

**Comment by dluetger** [comment]
Oh wait missed the actual text of the issue. So I changed it so there is actually breathing room. Is the new style of the -or- between the buttons mission critical at this time?
