### ISSUE TITLE
Emails not being sent to rider when driver approves/denies them to driver's carpool

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#329]
Emails are not being sent to the passenger when driver approves/denies them to driver's carpool

**Comment by flynnwastaken** [comment]
Approval email sent
![screen shot 2017-10-16 at 9 58 50 am](https://user-images.githubusercontent.com/32378726/31631282-1ed943c4-b26e-11e7-8f44-19c27a32f3fe.png)
But created a new bug: #439
