### ISSUE TITLE
Consider changing "Carpools" button to "Add a ride/Find a ride" buttons

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#33]
The "Carpools" button at the top left of the screen takes the user to a screen with two buttons: "Look for a Ride" and "Add your Ride". Since we're not short of screen real estate, maybe replace the "Carpools" button with two buttons for "Look for a Ride" and "Add your Ride" (or even "Passengers" and "Drivers")

**Comment by iandees** [comment]
I experimented with this and on mobile the header is pretty tight already (especially if you're signed in and the name is up there).

I think I'd want to see the word "Carpools" replaced with a better name for the product ("Nomad"?) or an icon or something.

**Comment by jillh510** [comment]
Could small-width windows/screens be a hamburger menu with two items?

**Comment by iandees** [comment]
I agree that finding and adding carpools should be more easily discoverable, though... maybe... yep a hamburger or something for logged in people?

**Comment by schloo** [comment]
fixed this int he global nav!
