### ISSUE TITLE
Fix the "Contact us somehow" placeholder on landing page

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#330]
On the main page their is a placeholder for contact us. 

It should have our nomad email address

<img width="827" alt="screen shot 2017-10-12 at 6 30 48 am" src="https://user-images.githubusercontent.com/17053096/31491947-167261f2-af17-11e7-8054-0b917638ae14.png">

**Comment by jillh510** [comment]
nomad-help@ragtag.org is the email address to use.
