### ISSUE TITLE
intercom not working

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#331]
Look into why intercom is not working

**Comment by engerm** [comment]
Unable to launch intercom from the page.

**Comment by iandees** [comment]
Intercom is set up correctly in the template, but I still don't see it. Do you need to enable it somehow on the Intercom side?

**Comment by iandees** [comment]
(See also https://docs.intercom.com/install-on-your-product-or-site/quick-install/install-intercom-on-your-web-app-for-logged-in-users)

**Comment by kielni** [comment]
Which page?

**Comment by kielni** [comment]
It's trying to run on http://nomad-staging.ragtag.org/ for me, but is blocked by Ghostery; are you running that or other ad/tracker blockers?
<img width="1081" alt="screen shot 2017-10-13 at 8 33 05 pm" src="https://user-images.githubusercontent.com/1649528/31572237-faa2f3f2-b055-11e7-9f86-2fd2cb6aed0c.png">

**Comment by engerm** [comment]
@kielni no add blockers. 

Tried on multiple browsers too. Have been unable to figure out why it's not working.

**Comment by iandees** [comment]
Please read my comment above. I think you need to enable something in intercom.

**Comment by engerm** [comment]
@bradyk fixed it.

Closing
