### ISSUE TITLE
Language Change and remove link

### ISSUE THREAD

**Issue by flynnwastaken** [RagtagOpen/nomad#332]
@schloo 
![screen shot 2017-10-12 at 12 46 20 pm](https://user-images.githubusercontent.com/32378726/31515874-9dd904f0-af4b-11e7-8927-6395d74cd632.png)

We can't say that this is a joint effort because they didn't do anything and didn't sanction this, it's untrue and gives the wrong impression. Could we get rid of the VA Dems link, change the link from ragtag.org to ragtag.org/nomad, and change the language to something like this:

"Nomad was built Ragtag, a team of tech volunteers that helps activists, organizers, non-profits, and candidates break down tech barriers to achieving their organizing goals. Nomad lets volunteers help their fellow volunteers get to where they can have the biggest impact.

Use Nomad to get volunteers to your campaign or find out more about Ragtag: "

**Comment by jillh510** [comment]
Assigning to a few folks to sign off on the proposed wording

**Comment by engerm** [comment]
Suggesting the following:

"Nomad was built by Ragtag, a team of tech volunteers who help activists, organizers, non-profits, and candidates break down tech barriers making it easier to achieve their organizing goals. Nomad lets volunteers help their fellow volunteers get to where they can have the biggest impact.

Use Nomad to get volunteers to your campaign or find out more about Ragtag: "

**Comment by schloo** [comment]
Updated this along with #330 . Other than this, is there any other thought we need to give to the home page content?
