### ISSUE TITLE
landing page: "Start your own carpool" incorrect

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#335]
The "Start your own carpool" links back to the Nomad landing page, which is the page the user is already on.

Current link:
https://nomad-staging.ragtag.org/

Should be "https://nomad-staging.ragtag.org/carpools/new", or something else that is more appropriate

**Comment by simonl2002** [comment]
I've verified this but don't have ability to edit labels.

**Comment by engerm** [comment]
label updated.
