### ISSUE TITLE
web template: no header if browser is not wide enough

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#338]
There is no header if the browser width is narrow, but it doesn't have to be that narrow for it to happen.

<img width="1285" alt="screen shot 2017-10-12 at 5 33 20 pm" src="https://user-images.githubusercontent.com/17053096/31520525-133c12c8-af74-11e7-934f-d5b25d706c12.png">

**Comment by schloo** [comment]
@engerm it's become part of the dropdown in the left menu (accessible by clicking the N)

**Comment by dluetger** [comment]
So do we still think this is an issue? This might be one of those things that is a usability feedback item rather than a straight-up bug.
