### ISSUE TITLE
Consistent python version

### ISSUE THREAD

**Issue by jmcarp** [RagtagOpen/nomad#356]
Based on https://sentry.io/share/issue/3232323036302e333639373537353831/, it looks like this app is running on python 3.6, but the dockerfile specifies 2.7: https://github.com/RagtagOpen/nomad/blob/master/Dockerfile#L1. Which python version(s) does this support? Probably best to run the same versions locally and on heroku.

**Comment by iandees** [comment]
It was initially designed to run in both, but it looks like we didn't quite keep up with that. The Dockerfile should be updated to use 3.
