### ISSUE TITLE
/carpools/starts.geojson discloses real address from long/lat coordinates

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#365]
The /carpools/starts.geojson discloses the real address (location) using the longitude and latitude. 

```
{
      "geometry": {
        "coordinates": [
          -76.989036, 
          38.902598
        ], 
        "type": "Point"
      }, 
      "id": "https://nomad-staging.ragtag.org/carpools/5d397fa3-b89d-4929-8eea-111f9c98aad7", 
      "properties": {
        "driver_gender": "self-describe", 
        "from_place": "New test", 
        "is_approximate_location": false, 
        "leave_time": "2017-10-20T09:00:00+00:00", 
        "leave_time_human": "Fri Oct 20 2017 at 9:00 AM", 
        "return_time": "2017-10-25T09:00:00+00:00", 
        "return_time_human": "Wed Oct 25 2017 at 9:00 AM", 
        "seats_available": 7, 
        "to_place": "123 Georgia Avenue Northwest, Washington, DC, United States"
      }, 
      "type": "Feature"
    }
```

Someone could put the long/lat coordinates in https://www.gps-coordinates.net/ and get the actual address.

**Comment by kielni** [comment]
If you are the driver or a confirmed rider, the coordinates are correct and you should be able to see that info. If you're not, the coordinates have a random +- 0.2 degrees added to them (a mile-ish) before they're sent to the browser. They're good enough for plotting an approximate circle on the map, but are not the actual coordinates.

see https://github.com/RagtagOpen/nomad/blob/master/app/carpool/views.py#L137 and https://github.com/RagtagOpen/nomad/blob/master/app/carpool/views.py#L72
