### ISSUE TITLE
Tests / ci / cd

### ISSUE THREAD

**Issue by jmcarp** [RagtagOpen/nomad#366]
It looks like this project could use some unit tests. I'm guessing they're missing for lack of time. I'd be happy to start writing tests if it would be useful, and get them running on your preferred ci service. And ditto for continuous deployment--if nothing else, heroku [review apps](https://devcenter.heroku.com/articles/github-integration-review-apps) can be really for checking out a patch without having to pull down code.

**Comment by iandees** [comment]
Yup! We could use tests all over the place. We're already using review apps in heroku, but they're hard to use because of oauth callback url limitations by Google and Facebook. Once we have tests we can figure out which ci service to use.

**Comment by iandees** [comment]
@jmcarp I can set up GitHub to do the branch checks. It would be very helpful to backfill tests. It might be useful/inspiring to add a code coverage step so we can watch that go up.

**Comment by iandees** [comment]
I'm going to close this for now as we're operating with Travis (#443) and the tests you wrote, @jmcarp. Let's keep moving by backfilling more tests 👍 .
