### ISSUE TITLE
edit carpool page no longer displays address or coordinates 

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#367]
When a driver edits one of their carpools the "Find a location on the map" input is empty. It should have the location visible to the the driver

<img width="720" alt="screen shot 2017-10-13 at 11 26 29 pm" src="https://user-images.githubusercontent.com/17053096/31572191-f99ce536-b06d-11e7-9298-b58dfaa52fd9.png">

```

<form method="post" class="form-page">
  | <input id="departure_lat" name="departure_lat" type="hidden" value="38.902598">
  | <input id="departure_lon" name="departure_lon" type="hidden" value="-76.989036">

...
...
...

<h4>Pickup / Dropoff Location</h4>
--
  | <label>Find a location on the map:</label>
  | <input type="text" id="location-seed"></input>
  |  
  |  
  |  
  | <label>Then drag the pin to your desired carpool pickup location:</label>
  | <div id="mini-map"></div>
  | <input id="departure_lat" name="departure_lat" type="hidden" value="38.902598">
  | <input id="departure_lon" name="departure_lon" type="hidden" value="-76.989036">
  | </div>
```

**Comment by iandees** [comment]
The "find a location" box is only there to help the user orient themselves in the map. We don't store the address anywhere separately from the name. The name is the address by default.

**Comment by jillh510** [comment]
Needs some UI attention to figure out the right approach

**Comment by dryan** [comment]
Why don't we just save the seed string and show it to the user on edit? Seems like a pretty simple approach to this.

**Comment by jillh510** [comment]
works for me
