### ISSUE TITLE
web template: Extra space on right side of homepage allows scrollover - Safari on Mac

### ISSUE THREAD

**Issue by flynnwastaken** [RagtagOpen/nomad#371]
![screen shot 2017-10-13 at 10 52 50 pm](https://user-images.githubusercontent.com/32378726/31573091-78ff7f6e-b069-11e7-8ffd-2103fbf3e5b3.png)

I can scroll right from the front page into some weird empty space on the homepage

**Comment by schloo** [comment]
Fixed #404
