### ISSUE TITLE
needs template: Bad Request needs nomad template

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#380]
The "Bad Request" page needs the nomad template

```
Bad Request

The CSRF token is missing.
```

<img width="1200" alt="screen shot 2017-10-14 at 7 06 15 pm" src="https://user-images.githubusercontent.com/17053096/31580047-ec7a373c-b112-11e7-9b18-8553656e2140.png">

**Comment by iandees** [comment]
A user should never see this. Did you do something to cause it or is there a bug somewhere?

**Comment by engerm** [comment]
I deliberately caused it. Checking some things...

**Comment by engerm** [comment]
Now has a template.
