### ISSUE TITLE
unable to manually enter dates "Start a new carpool"

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#383]
Unable to manually enter a date on the "Start a new carpool" using the MM/DD/YYYY format.

This is a show stopper since the calendar widget does not work in FF and Safari.

This is related to /carpools/new - unable to use the calendar selector in FF and Safari #271 

<img width="1200" alt="screen shot 2017-10-14 at 9 02 43 pm" src="https://user-images.githubusercontent.com/17053096/31580611-096222c8-b123-11e7-8161-1dc698ddd775.png">

**Comment by phildini** [comment]
Hi there! I was just able to add a date locally on chrome using a mac, and the carpool saved. Is there any more detail you can provide about what went wrong?

**Comment by engerm** [comment]
Just checked.

Calendar widget works in chrome.

Have to manually enter dates using the CCYY-MM-DD format for safari and firefox
