### ISSUE TITLE
template: Privacy & Terms padding issue

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#386]
There is no padding between the  "Privacy Policy" and the line above it and ""Privacy Policy" and the paragraph below it. Seems like there should be padding.

Same applies for the "Terms" header

![screen shot 2017-10-14 at 10 10 03 pm](https://user-images.githubusercontent.com/17053096/31580975-85f96450-b12c-11e7-96cb-d592db493708.png)

**Comment by schloo** [comment]
fixed #400
