### ISSUE TITLE
new user unable to create profile on mobile

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#388]
A new user gets an error 500 when creating their profile for the first time

New user (completely new) is unable to create their profile. They get an error 500

Steps:

1) click start your own carpool

2) login with gmail

3) select gmail account

4) on edit profile page, fill in profile page

5) save changes

- get internal server error

![img-2419](https://user-images.githubusercontent.com/17053096/31581039-6681d7fe-b12e-11e7-8721-8390cb90d3a9.PNG)

**Comment by engerm** [comment]
Confirmed using on a Mac with FF too

**Comment by iandees** [comment]
https://sentry.io/share/issue/3232323036302e333730353433313634/
