### ISSUE TITLE
Improve self-described gender phrasing

### ISSUE THREAD

**Issue by simonl2002** [RagtagOpen/nomad#397]
When a self-described gender is displayed it shows as "self-describe as X." That should be "self-described as X" or maybe "gender self-described as X" or something else that's more grammatically pleasing.

**Comment by engerm** [comment]
Looks good now.

<img width="1360" alt="screen shot 2017-10-15 at 10 38 12 pm" src="https://user-images.githubusercontent.com/17053096/31592934-8af1d58c-b1f9-11e7-8a48-5021c5300b78.png">
