### ISSUE TITLE
able to view old rides & request a ride in them

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#412]
Any authenticated user is able to view rides that happened in the past if they know the UUID.

Example:
https://nomad-staging.ragtag.org/carpools/52beea1e-357d-4bca-80ef-21c210b6c020

Actual Results:
1) any user able to view old carpool
2) any user able to request a seat to an old carpool

Expected Result:
- user would be unable to view an old carpool unless they were part of that carpool
- user would be unable to request a seat to an old carpool

**Comment by engerm** [comment]
This is related to `webui: any user can see old/canceled rides` #169 


https://github.com/RagtagOpen/nomad/issues/169

**Comment by tkell** [comment]
Closing with #581.
