### ISSUE TITLE
web template: My Carpools page - carpools in which you are a passenger and in which you are a driver not immediately visually distinguishable

### ISSUE THREAD

**Issue by flynnwastaken** [RagtagOpen/nomad#414]
The "You’re the driver of this carpool. Thanks for driving!" and "You’re confirmed for this carpool. Have a good trip!" banners under rides on the My Carpools page are the same color and look very similar. Carpools appear to be sorted chronologically, rather than by user role (rider or driver), so this visual similarity is confusing and makes it difficult to figure out ride statuses.

Two possible ways to change:
1. different colored banners for "you're the driver" and "you're confirmed" messages
2. sort in two sections by whether you are offering the ride or requesting the ride, and chronological within those categories, no change to banner color necessary

**Comment by jillh510** [comment]
This is a dup of #515, closing.
