### ISSUE TITLE
Map Zoom and Pins issue - Safari on Mac

### ISSUE THREAD

**Issue by flynnwastaken** [RagtagOpen/nomad#415]
![screen shot 2017-10-15 at 10 07 18 am](https://user-images.githubusercontent.com/32378726/31587130-bf55cf9a-b190-11e7-8ebb-fd5c22e6c3f4.png)

When I searched DC, it showed me the whole eastern half of the country, so there is a zoom problem. And the only visible pins were MN and PA rides, which I created. The "general area" color spots on the map only show up if you zoom in a lot.

**Comment by flynnwastaken** [comment]
The "general area" color spots on the map also are not clickable, is that intentional?

**Comment by flynnwastaken** [comment]
Steps:
1. Log in
2. Create a carpool
3. Attempt to find a carpool

**Comment by drabinowitz** [comment]
hmm is this for sure a Safari issue? This might be more an issue of returning the nearest trip. I got this also on Chrome. I think this has to do with the nearest addresses returned.

**Comment by drabinowitz** [comment]
I'm not certain if the location name is actually getting used in the search query. That when you enter a location the search it's not used to determine the loc_lat or loc_lon

**Comment by drabinowitz** [comment]
okay nevermind i was able to trace it through
