### ISSUE TITLE
Change text on main page to be about campaigns

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#42]
The text on the main page should reflect that people are carpooling to help campaigns. Maybe "Find carpools heading to campaign offices".

**Comment by iandees** [comment]
Existing text is mostly a placeholder. I'd like to see a bit more text designed to draw people in and use the site.

**Comment by jillh510** [comment]
Totally understood. If we want to show the site to campaign managers, though, it might make more sense to them if it had something to do with elections.

**Comment by schloo** [comment]
fixed up a bit (would still be nice to get a copywriter eventually, but i think it's good for MVP)

![image](https://user-images.githubusercontent.com/2453862/31317069-2e7854c6-ac08-11e7-8eee-81050d9f3334.png)
