### ISSUE TITLE
template: Method Not Allowed needs nomad template

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#422]
Can easily test using

https://nomad-staging.ragtag.org/logout

<img width="1360" alt="screen shot 2017-10-15 at 5 55 24 pm" src="https://user-images.githubusercontent.com/17053096/31589585-2b68b36e-b1d2-11e7-8a00-5df41d509262.png">

**Comment by iandees** [comment]
Dupe #253.
