### ISSUE TITLE
in FF, the "Find rides near you" does not display last carpool entirely 

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#424]
The left scroll with the carpools does not show the last carpool fully in FF on Mac..

When testing, please check all major browsers.

<img width="1332" alt="screen shot 2017-10-15 at 6 15 09 pm" src="https://user-images.githubusercontent.com/17053096/31589764-e7d3188a-b1d4-11e7-9687-89266b736d7d.png">

**Comment by dryan** [comment]
This is no longer the case.
