### ISSUE TITLE
unable to delete a destination

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#426]
get a server 500 when deleting a destination

**Comment by iandees** [comment]
https://sentry.io/share/issue/3232323036302e333730393330363334/

**Comment by iandees** [comment]
Missed some changes when I was doing email stuff in #392.

**Comment by engerm** [comment]
Still getting an error 500.

**Comment by iandees** [comment]
Different reason this time. Fixed it in #432.

**Comment by engerm** [comment]
Abe to delete now
