### ISSUE TITLE
Can't log out, returned to homepage - Safari on Mac

### ISSUE THREAD

**Issue by flynnwastaken** [RagtagOpen/nomad#437]
Steps
1. Open nomad-staging.ragtag.org already logged in from previous session
2. Try to log out

Happened from homepage, from My Carpools page, from find a ride map page

**Comment by iandees** [comment]
Can you give some more details here?

**Comment by iandees** [comment]
How did you logout? What page were you on?

**Comment by iandees** [comment]
I'm going to close this because I can't figure out what the issue is. Logging out works for me on Safari from all the pages I've tested it on.
