### ISSUE TITLE
Email not filling in ride details

### ISSUE THREAD

**Issue by flynnwastaken** [RagtagOpen/nomad#439]
![screen shot 2017-10-16 at 9 54 22 am](https://user-images.githubusercontent.com/32378726/31624723-76223f3e-b258-11e7-92ac-93c603f07c5f.png)
@iandees 

The places where info from the site should be filling into blanks in the ride_requested email template are simply blank

Also in ride_approved email
![screen shot 2017-10-16 at 9 58 50 am](https://user-images.githubusercontent.com/32378726/31627766-417bb99e-b263-11e7-8d1a-3142e7b33d09.png)

**Comment by jkriss** [comment]
`Person.as_dict()` only returns uuid, so name is not available for the template: https://github.com/RagtagOpen/nomad/blob/master/app/models.py#L106

Should be:

```python
    def as_dict(self):
        return {
            'uuid': self.uuid,
            'name': self.name
        }
```

Templates reference `carpool['leave_place']`, but `leave_place` doesn't appear to be in the Carpool model, but `from_place` is an attribute: https://github.com/RagtagOpen/nomad/blob/master/app/models.py#L150

`to_place` is also not an attribute of Carpool. I'm assuming it's part of Carpool.destination, although Destination has the same problem where `as_dict()` only includes the uuid: https://github.com/RagtagOpen/nomad/blob/master/app/models.py#L236
