### ISSUE TITLE
Asked to log in when already logged in

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#44]
Steps to reproduce
- Be logged out
- Start up Safari, go to https://ragtag-carpool.herokuapp.com
- Click "Look for a ride"
- Log in via FB using the button in the top right. See that the upper right says "Signed in as jill.huchital"
- Click "Carpools" in the top left
- Click "Add your ride"
- Quit Safari
- Restart Safari, you're on the "Add your Ride" page, logged in
- Click "Carpools", then "Look for a ride"

Result:
On the "Look for a ride" page, but not logged in

**Comment by iandees** [comment]
Do you have Safari configured to throw away cookies or session information when you close? It seems like you might have been seeing a cached page when you started Safari the second time and saw yourself logged in?

**Comment by jillh510** [comment]
If I shift-reload, I'm logged out. So maybe it's a cached page. Any way to bust the cache?

**Comment by iandees** [comment]
I think Safari holds onto a cache of the page so that when you restart Safari it has something to load right away. I'm not sure there's a way to fix that other than reloading like you did... It's a Safari "feature".

**Comment by engerm** [comment]
I'm looking at 44 ( https://github.com/RagtagOpen/nomad/issues/44 ) and the same is happening to me. I think it's a cache thing. Also happens on Chrome.

@jillh510 @iandees - I'm going to close this since it's cacheing. If you think it should be addressed then let's reopen it.
