### ISSUE TITLE
"Create carpool" people count change: total seats, empty seats, info field for existing riders

### ISSUE THREAD

**Issue by flynnwastaken** [RagtagOpen/nomad#468]
Right now the assumption is that the driver is the only one in the car, and the number they select from the "Number of Passengers" dropdown is the number of empty seats they have. However, many people carpool with friends, spouse, or other family members. They may have already made these arrangements before they get to our platform. We don't capture that and therefore 1) users may be confused or upset 2) we can't give the campaign accurate numbers of canvassers to expect at the staging location 3) we slightly underestimate out impact =[ 

Nomad2016 had a section where the carpool creator filled in info for the driver and any riders already part of the carpool

I suggest we have a dropdown for total seats, a dropdown for empty seats, and up to (total seats) - (empty seats) addable info collection fields for riders already known/planned

**Comment by jillh510** [comment]
Will solve this by allowing drivers to share links.
