### ISSUE TITLE
Add more details to "My rides" page

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#47]
Make the "Add your ride" page a place where a driver can manage all of his/her carpools: adding new ones and seeing a list of existing carpools, with the ability to approve passengers directly from that page.

**Comment by iandees** [comment]
@jillh510 take a peek to see if what I did here makes sense.

**Comment by jillh510** [comment]
Is there a reason the carpool details (especially the dates) and "cancel" button aren't available on the "Your Carpools" page?

Also, it's showing all my carpools, even those in the past. Maybe separate into "Upcoming" and "Past", or even make this page "Your Upcoming Carpools" with a link to get to the ones in the past.

**Comment by iandees** [comment]
I'm realizing now that the "My rides" section should be a list of `<div>`'s with more details in them rather than a table. It should also include rides that you're a rider in, not just rides you are a driver for.

@schloo, can you mock up a page that shows a list of rides associated with the current user? It should include details about dates, from/to locations, and status (driver, accepted/canceled, etc.).

**Comment by engerm** [comment]
My Rides should show rides for passengers #324 

Rides show up for drivers, but riders are unable to see what rides they belong to

**Comment by engerm** [comment]
No. This issue (#47) is for the drivers, and #324 is for the passengers.

**Comment by schloo** [comment]
@jillh510 @engerm I believe the intent was to have these 2 be the same screen, so that if someone were to drive one day and carpool the next, all their rides would show up here.

**Comment by schloo** [comment]
@iandees just submitted PR #372 . i couldn't figure out the logic with a cancelled ride, can you help me out there?

**Comment by iandees** [comment]
The My Rides page has some more details now (including drivers' rides and riders' rides):

![image](https://user-images.githubusercontent.com/261584/31578858-576ec5ea-b0ef-11e7-8e27-440456601650.png)
