### ISSUE TITLE
Form validation errors should be styled differently

### ISSUE THREAD

**Issue by jmcarp** [RagtagOpen/nomad#474]
It's hard to distinguish form validation errors (e.g. "Please select a gender") from field labels (e.g. "We ask for this information to ensure..."). Validation errors should be styled differently from labels so that users can tell when submissions are invalid.

**Comment by iandees** [comment]
Yep, when the error messages were turned into `<label>` tags we lost the red styling. @schloo, can you take a look at the CSS so that the error messages stand out more from the other nearby `<label>`s?

**Comment by jillh510** [comment]
looks to be working now
