### ISSUE TITLE
Feature request: Join link

### ISSUE THREAD

**Issue by flynnwastaken** [RagtagOpen/nomad#482]
We should provide carpool drivers with a link to join their carpool directly. They can copy and share it with anyone they'd like to be in their carpool before randos find them on the map

Related to #481

**Comment by kielni** [comment]
What happens when someone clicks on the link?
  - are they required to go through regular create account flow?
  - if not, what's the minimum we need to collect?

**Comment by tkell** [comment]
@jillh510, @kielni, what are your thoughts on implementing this?

- The more correct way would be to force them to create an account and login. 
- There's maybe a hack where they enter just a name and an email?  And probably create an account for them in secret?
- Ugh, there's also a race condition in here, but I propose we ignore it until it becomes a problem.

In terms of how this relates to #481, I feel like #481 is a pretty simple "How many people are already in the car" dropdown - no need to  create user accounts if the carpool creator knows that someone is coming.

**Comment by jillh510** [comment]
They should go through the regular account flow.

**Comment by tkell** [comment]
Ok, it looks like this just needs a redirect path from the "login" form.  Will wrassle with it.

**Comment by tkell** [comment]
Looks like this is working when logging-in existing users, unsure if it works for creating new users.

**Comment by tkell** [comment]
This does _not_ work when creating a new user.  Will work on it.

**Comment by tkell** [comment]
With #564, this now works for both new and existing users - one can just link to http://localhost:5000/carpools/<carpool-id>.

**Comment by iandees** [comment]
@tkell the desire here is to send a link to a specific carpool (as an invite) and have them sign up/sign in and eventually get to the point where they confirm they want to request a spot on the carpool. What did you mean by linking to /carpools?

**Comment by tkell** [comment]
Ugh, @iandees, sorry, missed my backticks in the above - you can link to each carpool via its id

**Comment by iandees** [comment]
Ah! Gotcha. This is probably good enough for now, but we might want to make a more purpose-built/-designed page for inviting people to a carpool. Maybe that could be another ticket (or we could re-open this one if we add more detail).

**Comment by tkell** [comment]
🚀
