### ISSUE TITLE
Ragtag is mis-capitalized in email footer

### ISSUE THREAD

**Issue by bradyk** [RagtagOpen/nomad#491]
Please change text to:

"Nomad by Ragtag"

<img width="500" alt="screen shot 2018-02-23 at 4 10 46 pm" src="https://user-images.githubusercontent.com/1565834/36622800-72cf576e-18b4-11e8-9d54-26117cb56b0d.png">

**Comment by bradyk** [comment]
Fixed it!

**Comment by iandees** [comment]
Fixed in https://github.com/RagtagOpen/nomad/commit/2d893d16ac8d1e95b030f4d64fc9422c24733cd2.
