### ISSUE TITLE
Profile save fails silently - possibly intermittent

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#496]
In testing the carpool tool, it looks like if fields aren't filled out properly on the profile, if you click "save changes" nothing happens. There's no error notification to let you know that your request for a ride or your setting up a carpool hasn't worked -- it just does nothing. (So if your profile name is only 2 characters instead of 3, or there's no phone number, etc.) Can we make sure to add a red indicator field to anything that's been improperly filled out to make sure that folks know 1.) What's incorrectly filled out 2.) That their request hasn't been submitted yet

(BTW this seems to be intermittent)

**Comment by iandees** [comment]
There is an error when trying to save invalid data on your profile:

![image](https://user-images.githubusercontent.com/261584/36743490-0c53e974-1bb0-11e8-968a-6d4b923159ae.png)

... it seems to have lost its red styling at some point, though.
