### ISSUE TITLE
HTML Email not displaying correctly for ride request

### ISSUE THREAD

**Issue by bradyk** [RagtagOpen/nomad#502]
The emails are truncated where the "click to approve/deny this request" link should be.

Viewing the "original" of the email show that the plain text has the correct link (https://nomad.ragtag.org/carpools/436f1b35-a4d3-4d9f-b6bc-52880662bf4b) and it looks like it also has the correct info for the HTML version.

<img width="1219" alt="screen shot 2018-02-28 at 3 04 40 pm" src="https://user-images.githubusercontent.com/1565834/36818310-53125082-1c99-11e8-96a3-bc8b3326ce51.png">

**Comment by bradyk** [comment]
Message ID | <151985879537.12.5248251674215762595@b7411bb4-31e0-4c2e-af57-41c089c60a54.prvt.dyno.rt.heroku.com>
-- | --
Wed, Feb 28, 2018 at 2:59 PM (Delivered after 4 seconds)
nomad-help@ragtag.org
brady@ragtag.org
Ian Dees requested a ride in carpool on 2018-03-01 09:00:00+00:00
PASS with IP 184.173.153.194 Learn more
'PASS' with domain mg.ragtag.org Learn more

**Comment by iandees** [comment]
The email template is missing a `"` after the URL.

**Comment by bradyk** [comment]
added said missing "
