### ISSUE TITLE
request: on /carpools/mine create buttons for View, Edit, and Cancel

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#503]
This is a request based on customer feedback:

Add buttons on the /carpools/mine page to View, Edit, and Cancel the carpool's details.

It is unclear that by clicking the "View details" allows a user to edit and cancel the ride.

**Comment by engerm** [comment]
<img width="1436" alt="screen shot 2018-03-04 at 2 21 07 pm" src="https://user-images.githubusercontent.com/17053096/36949514-8608c810-1fb7-11e8-8b17-a3c41699e533.png">

**Comment by iandees** [comment]
Drivers now have this view for their carpools:

![image](https://user-images.githubusercontent.com/261584/36950411-25452894-1fbb-11e8-97fe-541a0d8f3291.png)

**Comment by engerm** [comment]
Looks to to me. Tested it out on staging.
