### ISSUE TITLE
/carpools/{UUID}: change "Edit your carpool" link into a button

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#505]
This is a request based on customer feedback:

Change the "Edit your carpool" link into a button.

**Comment by engerm** [comment]
<img width="1436" alt="screen shot 2018-03-04 at 2 29 26 pm" src="https://user-images.githubusercontent.com/17053096/36949609-aa35ff68-1fb8-11e8-9973-c94e487a1830.png">

**Comment by iandees** [comment]
Didn't mean to close it. It's on staging. Close when tested.

**Comment by iandees** [comment]
Looks like this:

![image](https://user-images.githubusercontent.com/261584/36950227-c506e474-1fb8-11e8-8120-788c21fe8c05.png)

**Comment by engerm** [comment]
Looks good to me. Tested on staging
