### ISSUE TITLE
change mobile menu order

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#506]
This is a request to change the mobile drop down menu from:

```
- Home
- Find a ride
- Give a ride
- Privacy & Terms
- My Rides
- Profile
_____
- Logout
```

to:

```
- Home
- My rides
- Find a ride
- Give a ride
_____
- Privacy & Terms
- Profile
- Logout
```

**Comment by engerm** [comment]
Note: "My Rides" should be consistent with other "rides"

Please change from "My Rides" to "My rides"

**Comment by iandees** [comment]
Looks like this now:

![image](https://user-images.githubusercontent.com/261584/36950320-fd02d8a0-1fb9-11e8-8a17-5b60d4a494ce.png)

**Comment by engerm** [comment]
Looks good to me.

Tested on staging.
