### ISSUE TITLE
Preview header text wrong on emails when rider is accepted.

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#512]
<img width="966" alt="nomad_bug" src="https://user-images.githubusercontent.com/2319837/42540013-be7c4e34-8451-11e8-82a2-9f5f5a4bb4e7.png">

**Comment by jillh510** [comment]
Also when a rider requests a ride.
![screen shot 2018-07-10 at 3 19 05 pm](https://user-images.githubusercontent.com/2319837/42540774-9e9f2926-8454-11e8-9123-6702662016c7.png)

**Comment by leeschumacher** [comment]
This comes from the wrapper file [app/templates/email/_wrapper.html#L97](https://github.com/leeschumacher/nomad/blob/0b6980171db4e442ce77e29341b37a9d26a89670/app/templates/email/_wrapper.html#L97).   We'll need to either remove the boilerplate or (better) add a block and override it based on the parameters.

**Comment by jillh510** [comment]
@FStephenQ do you think you'll get to this one this week, or shall I look for backup?
