### ISSUE TITLE
Email to driver looks strange if rider didn't provide a phone number.

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#513]
"Rider McRider can be contacted at examplerider@gmail.com or (email preferred)."

Looks like the empty string is copied into a template that assumes a string will be there.

**Comment by jillh510** [comment]
also a problem on emails to the passenger if the driver didn't provide a phone number.

**Comment by iandees** [comment]
This was fixed in https://github.com/RagtagOpen/nomad/pull/556.
