### ISSUE TITLE
Labels at bottom of carpool dashboard inconsistent

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#531]
(running on staging, which includes the fix for #521)

Labels on pagination at the bottom of the dashboard are inconsistent ("Newer carpools/Older users")
![screen shot 2018-07-20 at 7 09 20 pm](https://user-images.githubusercontent.com/2319837/43031139-6e636e62-8c50-11e8-88e7-59f7daa4bb30.png)

**Comment by iandees** [comment]
Is that list in the admin?
