### ISSUE TITLE
Running tests via Docker breaks the main db

### ISSUE THREAD

**Issue by tkell** [RagtagOpen/nomad#546]
Run `docker-compose run nomad pytest`, then try to boot the app via Docker.  

You'll see a `sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "people" does not exist` error.

This can be worked around by rm-ing one's Docker containers and rebuilding them, but that's a pretty poor workaround.

cc @joearasin, @iandees.

**Comment by joearasin** [comment]
Not just a docker thing. Running tests creates/drops the schema, whatever that may be, and drops it w/o dropping the alembic tables so running "migrate" doesn't put things back together again. The test suite should probably spin up its own test schema.
