### ISSUE TITLE
Make "Ride Requests" label in Carpools dashboard clearer

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#550]
The "Ride Requests" label isn't clear at first glance whether it's "All requests (pending and approved)" or "Pending Requests". Can the label be changed to what it actually is?

**Comment by iandees** [comment]
Can you take a screenshot or post a URL of the page you're talking about?

**Comment by jillh510** [comment]
![screen shot 2018-07-28 at 8 56 47 am](https://user-images.githubusercontent.com/2319837/43358295-29dd04fc-9244-11e8-8af7-a1624a66c372.png)

**Comment by rdhyee** [comment]
The "Ride Requests" column is the total of rides with `approved` and `requested` status.   [nomad/list.html at 2ac5328d04243711d6f4d469c8737ec00cbd7b49 · RagtagOpen/nomad](https://github.com/RagtagOpen/nomad/blob/2ac5328d04243711d6f4d469c8737ec00cbd7b49/app/templates/admin/carpool/list.html#L37):

>  <td>{{ carpool.riders_and_potential_riders|length }}</td>

[nomad/models.py at ffa7cc894ede1726d40ed093912f54a2ca556b85 · RagtagOpen/nomad](https://github.com/RagtagOpen/nomad/blob/ffa7cc894ede1726d40ed093912f54a2ca556b85/app/models.py#L199-L201):

    @property
    def riders_and_potential_riders(self):
        return self.get_riders(['approved', 'requested'])

So it sounds like the column header should be something like ""All requests (pending and approved)"

**Comment by dryan** [comment]
@jillh510 you good with this?
