### ISSUE TITLE
500 error when logged-out user clicks on a carpool

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#551]
On Android, if that makes a difference.
- Went to nomad.ragtag.org
- Allowed the app to use location info
- Clicked "Find a Ride"
- Clicked the first carpool on the "Find rides near you" list

Got a 500 error.

**Comment by iandees** [comment]
https://sentry.io/share/issue/19ea2dc1e3694a7b97eb8105387085d2/

This is happening because we're using `has_roles()` and an anonymous user doesn't have that function.

**Comment by iandees** [comment]
Sorry, @sjohnson540! I didn't see you had assigned this to yourself.
