### ISSUE TITLE
Pagination text on "Drivers and Riders" dashboard, off-by-one

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#566]
on https://nomad.ragtag.org/admin/drivers_and_riders, this is how the pagination text looks:

![screen shot 2018-07-30 at 2 09 02 pm](https://user-images.githubusercontent.com/2319837/43423783-287b8650-9402-11e8-8571-7197e2e0e76e.png)

Looks like the number in the center should be page + 1.

**Comment by kdechant** [comment]
On closer inspection, it seems that the pagination isn't working at all. I'm investigating.
