### ISSUE TITLE
If the user is an admin, add an "Admin Tools" item to the menu

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#568]
If the user is an admin, add a menu item "Admin Tools" to the user menu, between "Profile" and "Logout", that goes to /admin.

**Comment by jillh510** [comment]
There's (last I looked, before @kielni's change), the rightmost menu item
in the horizontal nav was itself a menu. Maybe add this item there?

**Comment by kdechant** [comment]
There is, but it only appears at >1200px screen widths. I think I'll need to implement it on smaller widths as well. Shouldn't be too hard.

**Comment by jillh510** [comment]
Here's what I see on small-width windows. So the "Admin tools" menu item could go between "Profile" and "Logout" here as well.
![screen shot 2018-08-06 at 12 09 08 pm](https://user-images.githubusercontent.com/2319837/43736200-9fe811d0-9971-11e8-8d1b-e14070aef9c5.png)

**Comment by kielni** [comment]
There are two menus:

The <1200px one is https://github.com/RagtagOpen/nomad/blob/master/app/templates/_template.html#L129 This is shown collapsed by default on xs (<768px) and is hidden (`.hidden-lg`) on >1200px. This version doesn't have a dropdown for the profile section, but it could if necessary.

The >1200px one is https://github.com/RagtagOpen/nomad/blob/master/app/templates/_template.html#L142 (`.visible-lg-block`) This version shows Profile and Logout [in a dropdown](https://github.com/RagtagOpen/nomad/blob/master/app/templates/_template.html#L162)

**Comment by kdechant** [comment]
I have an idea for how to proceed with this. I'll try to put something together tonight.

**Comment by jillh510** [comment]
@kdechant any luck? Or did your schedule go nuts, so someone else should grab this?

**Comment by kdechant** [comment]
Sorry that took a while, but I'm back and got the PR opened.
