### ISSUE TITLE
Genericize nomad.ragtag.org

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#574]
We're going to start demo'ing Nomad to campaigns and organizations soon, so the version on nomad.ragtag.org shouldn't have the Swing Left branding.

**Comment by kielni** [comment]
The branding is via config file now; details are in [Branding section of README](https://github.com/RagtagOpen/nomad#branding)

Looks like https://nomad.ragtag.org/ has the default (Ragtag) branding.

**Comment by jillh510** [comment]
d'oh. you're right.
