### ISSUE TITLE
Add Zendesk widget to main page

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#575]
On the main page, add a Zendesk widget that goes to Campaign Helpdesk. Also, change the current text from "Email the Nomad team for help: nomad-help@ragtag.org." to "Email the {{BRANDING_ORG_NAME}} team for help: {{ BRANDING_SUPPORT_EMAIL }}"

**Comment by tkell** [comment]
Email text done with https://github.com/RagtagOpen/nomad/pull/580.  

It looks like one needs a Zendesk account to access a widget – that should probably not be set up by me?

**Comment by jillh510** [comment]
Yeah, I think Brady's the one with that particular superpower

**Comment by jillh510** [comment]
Here are the instructions and the snippet: 
"Copy the following script and paste it into your website's HTML source code before the closing </head> tag.
This code must be inserted into every page you want to show the widget on. Note that the widget will not slow down your web pages."


<script id="ze-snippet" src="https://static.zdassets.com/ekr/snippet.js?key=19972695-e94b-40d7-be27-3f1c22dc0bc5"> </script>

**Comment by tkell** [comment]
Merged with #586 !
