### ISSUE TITLE
no way to search for a location on screens < 1200px

### ISSUE THREAD

**Issue by kielni** [RagtagOpen/nomad#578]
/carpools/find needs a search box

on screens wider than 1200px, there's a text input in the navbar: Find a ride near Zip code or City, State

on smaller screens, there's no text input anywhere on the page -- the only way to search is by browser geolocation

**Comment by kielni** [comment]
I started to look into this and found that the app doesn't actually do anything at all with the user-entered location info:
  - the [/carpools/find view erases the user query](https://github.com/RagtagOpen/nomad/blob/master/app/carpool/views.py#L55) from the context unless the query string also contains float lat and lng values
  - the /carpools/find.html template [fits the map to the results](https://github.com/RagtagOpen/nomad/blob/master/app/templates/carpools/find.html#L103), regardless of what the user entered

@jillh510 is this intentional? Should we be using  [Google's geocoding API](https://developers.google.com/maps/documentation/geocoding/usage-and-billing ($5/1000) to convert user input into coordinates? Or should we remove the input boxes and instruct the user to browse for a location by panning/zooming the map?

**Comment by jillh510** [comment]
We should geocode the ZIP code and zoom the map.

**Comment by jillh510** [comment]
(and there's still an open question whether /find should have a text input for the ZIP code. Working on that)

**Comment by jillh510** [comment]
closing this one and opening a separate one about the zoom
