### ISSUE TITLE
text input color on home page

### ISSUE THREAD

**Issue by kielni** [RagtagOpen/nomad#579]
should be light color; too hard to read dark gray against dark blue

<img width="626" alt="screen shot 2018-08-08 at 5 25 35 pm" src="https://user-images.githubusercontent.com/1649528/43871157-261fb4b4-9b30-11e8-92a2-7a4cf7c205a6.png">

screenshot from Mac Chrome; same issue on Mac Firefox but looks fine on Safari

**Comment by kdechant** [comment]
I think we're better off with a white form field. (Didn't it used to be white?) So I implemented that in the PR and also changed the button color to green to make it stand out. (If people don't like that color just let me know and I'll change it to something else.) Increased the font size while I was at it.
