### ISSUE TITLE
Ask users to specify gender before creating/joining a carpool

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#59]
To support single-gender carpools, we'll ask users for their gender, and then display it to potential passengers/drivers. This issue covers asking for the user's gender.

The Profile page should allow the user to specify a gender. The choices are
Female
Male
Non-binary/ third gender
Prefer to self-describe _________________
Prefer not to say

If a driver hasn’t specified a gender when they set up a carpool, ask for their gender on the carpool setup page. “Prefer not to say” counts as specifying a gender.
If a passenger hasn’t specified a gender when they set up a carpool, ask for their gender when they apply to join a carpool. “Prefer not to say” counts as specifying a gender.

**Comment by iandees** [comment]
@jillh510 This and #60 should be on the heroku app for your testing. Some limitations for now: the gender field is a clear-text field. I already had this implemented and a drop-down + free-text would require some extra javascript.

**Comment by jillh510** [comment]
I think we can afford the extra Javascript :). The issue with a clear-text field is that there's no way for the person to understand that "Prefer not to say" is a valid option.
