### ISSUE TITLE
Top nav should always have Give a Ride

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#597]
At certain screen sizes, the top nav doesn't contain the "Give a Ride" button, nor does it appear on  /carpools/find. The top nav should always have "Give a Ride.
![screen shot 2018-08-14 at 10 10 15 am](https://user-images.githubusercontent.com/2319837/44106732-43566cc0-9faa-11e8-8dc5-2ccf9d0ce241.png)

**Comment by jillh510** [comment]
Oh, it looks like "Find a ride" is a menu that also has "Give a ride". But "Give a ride" with a location doesn't make a lot of sense.

**Comment by dryan** [comment]
Yeah if we change the dropdown to just be text "Find a ride near" make the search input a bit narrower, there should be room for "Give a ride" as a link after.

I also suggest button a search button next to the input. A lot of users don't know they can hit enter to submit a form. A tiny one with a magnifying glass would do.

**Comment by kdechant** [comment]
Here's another idea:
* Remove the form from the header and make the location auto-suggestion work on the big blue form on the home page. New visitors will be drawn to this anyway.
* Make the top nav be all links, like it is on medium breakpoints already.

This would give us more room in the header at some sizes, and also would allow us to streamline the nav bar code.

Thoughts?

**Comment by jillh510** [comment]
I like having the ZIP code entry in the header for people who (1) don't allow the app to know their location, and (2) are in the UI, changing their profile for instance, and wouldn't get that they need to go back to the splash page if they want to enter a location.

**Comment by kdechant** [comment]
The PR #658 fixes this. Here's a preview of how it looks:

![image](https://user-images.githubusercontent.com/727401/45067834-a4f74500-b079-11e8-8d83-923c6983c12b.png)
