### ISSUE TITLE
Communicate drivers/passengers' genders to each other

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#60]
To support single-gender carpools, we'll ask users for their gender, and then display it to potential passengers/drivers. This issue covers how the gender is communicated to other users.

On the page that displays carpools with open space, list the driver's gender. The choices are
Female
Male
Non-binary/ third gender
Self-described (whatever the driver filled into that field)
Prefer not to say

When a passenger applies to join a carpool, the passenger's gender should be communicated to the potential driver in the email.

**Comment by engerm** [comment]
The gender so communicated of a driver when a rider sees the lists of available carpools.

The gender is also communicated to the driver when allowing/denying a rider.

Closing issue.

Further requests, such as having this information be shared via email, should be tracked in a new issue.
