### ISSUE TITLE
For each destination, have a "destination page" that only lists carpools going to that destination

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#615]
For each destination, have a page at a unique URL that filters out all carpools except the ones going to that destination. An example might be vote-jane-doe-carpools.ragtag.org/campaign_office or vote-jane-doe-carpools.ragtag.org/canvass-meetup-location.

Use case is: campaign staff can give this URL to people who want to come to a particular event.

**Comment by jillh510** [comment]
@iandees can this issue be closed?

**Comment by iandees** [comment]
Yep, looks like it after #645. We can file new issues for other changes to that page.
