### ISSUE TITLE
Branding on email footer?

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#617]
Opening this as a reminder to discuss: should the branding in the footer of emails be "Nomad by Ragtag" or partner branded?

![screen shot 2018-08-22 at 9 06 52 am](https://user-images.githubusercontent.com/2319837/44475801-d50b0680-a5ea-11e8-98f9-39d235346f51.png)

**Comment by jillh510** [comment]
Change upper line to "Brought to you by <BRANDING_ORG_NAME> and Ragtag"
Remove lower line.

**Comment by AaronSofaer** [comment]
Do all emails have a branding org?

**Comment by AaronSofaer** [comment]
Never mind, I see that there is a default in the configs file. Hooray!
