### ISSUE TITLE
The color on the help widget clashes

### ISSUE THREAD

**Issue by kcaffall** [RagtagOpen/nomad#619]
The color on the help widget clashes. Should match the Nomad color scheme.

**Comment by jillh510** [comment]
https://support.zendesk.com/hc/en-us/articles/226005528-Changing-the-color-of-the-Web-Widget-Chat-Widget-

**Comment by jillh510** [comment]
Fixed in Zendesk admin tool, maybe we need to wait for the change to propagate?

**Comment by jillh510** [comment]
yes, now is blue like the links
