### ISSUE TITLE
Ride request confirmation page - carpool details

### ISSUE THREAD

**Issue by kcaffall** [RagtagOpen/nomad#627]
“Carpool Details” on the top section has info about the carpool destination, etc. but “Carpool Details” on the bottom part has the driver gender. Either the name of one of the fields should be changed, or we need to verify what is supposed to be displaying there.

![image](https://user-images.githubusercontent.com/42283377/44594838-24cd0780-a77c-11e8-9828-6db3195a1db7.png)

**Comment by kielni** [comment]
Same as / very closely related to https://github.com/RagtagOpen/nomad/issues/567
