### ISSUE TITLE
Zoom on the map isn't working

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#643]
When searching for carpools, the map is zoomed to the entire USA. It should center on the user's location and have a reasonable radius (100 miles?)

**Comment by tkell** [comment]
Want to make sure of the spec here - if I search for carpools near an an address, should it center on the location I search for, or my current location?

**Comment by jillh510** [comment]
The location you search for

**Comment by jillh510** [comment]
Agreed that the third item should be a separate ticket; I'll go ahead and file it. In real-world usage, it shouldn't be an issue.

Thanks for the detective work to figuring out that the issue only arises when the user puts in a search location.
