### ISSUE TITLE
Display cancelled rides with "cancelled" status on My Rides page

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#650]
From @kdechant: 

In my experience (e.g., on Meetup), there are some users who tend to just delete things without notifying anyone that they're doing it. For this reason, it would be nice to have a "cancelled" status with a message, in case a rider doesn't see the email notification that it's been cancelled.

I think it would also be good to have the cancelled carpools appear on the rider's "My Rides" page (with a visual indicator like strike-through) to give the riders another indication that it was cancelled.

I'm not suggesting that there be any action available once a carpool has been cancelled; just information about what happened.

**Comment by kdechant** [comment]
Worked on this along with #199 because it just made sense to do them both at the same time.
