### ISSUE TITLE
Blue carpool circles should have a minimum pixel size

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#651]
There are blue circles on the map for where the carpools leave from. However, these get smaller the further out the map is zoomed. So if all 3 are in the same city, you can see them, but if they're spread out over multiple states, the markers shrink to the point where they're invisible. This makes it not obvious why it zooms to a specific area. 

The blue circles should be big enough, regardless of the zoom level on the map, that they're visible.

**Comment by kdechant** [comment]
The current marker is a "circle" type, which has a radius in meters. That doesn't really make a lot of sense on our map. It's meant as more of a data visualization thing.

There are other symbols (including a "circle marker" symbol) that have the same radius in pixels regardless of zoom level. I'm looking at using one of those.
