### ISSUE TITLE
First-time sign in throwing 500 

### ISSUE THREAD

**Issue by AaronSofaer** [RagtagOpen/nomad#667]
Tried to sign in on a new incognito window to my aaron@ragtag Google account. When I got redirected back to the Nomad site, I had an "internal server error" message. Trying to sign in again made it work just fine.

**Comment by jillh510** [comment]
yup, happening for me too

**Comment by iandees** [comment]
Which site were you using?

**Comment by AaronSofaer** [comment]
Staging, for me

**Comment by iandees** [comment]
I don't think I have seen anything come through on Sentry ... I don't have easy access to it right now though. If someone checks that'd probably have useful information.

**Comment by kcaffall** [comment]
Here's the error from the dev tools in Chrome:
google?code=4%2FVwB7rRWrXaiRDk3dEuBxk--7tDv21WlSKPmh20nOEdjNuOF6tnA8OG8aaX061pMUECt9mlESEPA_IKvxSBVngsA:99 Uncaught **ReferenceError: Raven is not defined**
    at google?code=4%2FVwB7rRWrXaiRDk3dEuBxk--7tDv21WlSKPmh20nOEdjNuOF6tnA8OG8aaX061pMUECt9mlESEPA_IKvxSBVngsA:99
(anonymous) @ google?code=4%2FVwB7rRWrXaiRDk3dEuBxk--7tDv21WlSKPmh20nOEdjNuOF6tnA8OG8aaX061pMUECt9mlESEPA_IKvxSBVngsA:99

**Comment by tkell** [comment]
I can't recreate it locally - anyone else?

**Comment by tkell** [comment]
OK, digging into the Sentry error, it looks like it is a `KeyError` for `name`, which strongly suggests line 109  of app/auth/oauth.py.

That dict comes from the OAuth provider, it looks like - and the dict, when it works for me locally, has all the keys that line 109 expects.  More digging.

**Comment by tkell** [comment]
This also works for me on Staging.  = \

**Comment by jillh510** [comment]
OH!!! This might be a known, uh, feature of Google Auth. Thor, when you logged in, did you use a gmail.com account, or a G-Suite account with a different domain? IIRC, OAuth to a Google account that's not a Gmail account isn't guaranteed to return the 'name'.

**Comment by tkell** [comment]
I am a gmail person!  

As per my chat with Ian in Slack, we could do something like:

```
108         if 'name' not in me:
109             me['name'] = ''
```

And thus ensure that the dict has the right keys?

**Comment by jillh510** [comment]
we should be sure that anyone whose name doesn't come via oauth is required to update it in their profile before offering or requesting a ride

**Comment by tkell** [comment]
Yep!  We enforce names to be at least 3 characters long:  `Please enter a name between 3 and 80 characters long.`

**Comment by jillh510** [comment]
let's close this issue. I'll open another for Sentry config.
