### ISSUE TITLE
Presentation of information on cancelled driver carpools needs work

### ISSUE THREAD

**Issue by AaronSofaer** [RagtagOpen/nomad#670]
This is what the rides page looks like if you have a fresh account, create a new carpool, then cancel it and return to the rides page.

![cancelthank](https://user-images.githubusercontent.com/2935149/45372057-dce21900-b5a0-11e8-86a1-3e96a468bfb3.PNG)

**Comment by jillh510** [comment]
If the carpool is cancelled, only show the red "This carpool has been canceled" message, not the "View details " button or the other info beneath.

**Comment by jillh510** [comment]
(if there's a cancellation reason, it should be displayed as well)
