### ISSUE TITLE
Denied ride request still shows as pending for passenger

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#688]
On Staging:
Logged in as user 1, created a carpool, logged out
Logged in as user 2, requested a ride in the carpool, logged out
Logged in as user 1, denied the ride request from user 2, logged out
Logged in as user 2, checked "My Rides". Carpool is still listed, and the carpool details page shows "Your ride request is pending".

(just to be sure, I logged back in as user 1, and the carpool details page shows "You denied this user").

Carpool page is https://nomad-staging.ragtag.org/carpools/b30fc947-eac4-4a33-8136-a10e20be5977

**Comment by gvelez17** [comment]
I think you need to save the request at line https://github.com/RagtagOpen/nomad/blob/master/app/carpool/views.py#L430

I'm not going to have time to do much on this so I don't want to make the change directly - I have to head to work now

**Comment by kdechant** [comment]
The data was saving OK. The "denied" message was never added to the templates. Fixed in the PR linked above.
