### ISSUE TITLE
Exporting Drivers and Riders should have a unique carpool identifier attached to them

### ISSUE THREAD

**Issue by flynnwastaken** [RagtagOpen/nomad#706]
I have an important request for data export. Exporting Drivers and Riders should have a unique carpool identifier attached to them sorting which carpool they're in. Sorting by that identifier would allow an organizer to get a full list of everyone in a particular carpool very easily, which right now can't be done. Even if you sort by both Date and Destination, there could be two carpools at the same time and they'd be jumbled up in one another. This could be especially important for an organizer filling a bus. @jillh510 can you review?

**Comment by jillh510** [comment]
Yes, makes sense. Looks like it mean adding a column for "carpool_id" to the CSV and outputting the field carpool_id, which I'm hoping comes back from that db query.
