### ISSUE TITLE
Correct verbiage for privacy policy (including branding elements)

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#712]
The first paragraph says "Arizona Democratic Party Nomad is provided by Arizona Democratic Party, and we have a firm commitment to your privacy and Internet privacy in general. " (Arizona Democratic Party is the BRANDING_ORG_NAME)

But a later paragraph refers to "www.azdem.org only uses your personal information for the original purposes it was given. " (www.azdem.org is the BRANDING_ORG_SITE_NAME)

Do these need to be consistent? To @bradyk for decision.

**Comment by bradyk** [comment]
@jillh510 I've DM'd you the new text on Slack.

But there are two changes need to be made in the placeholder text def or whatever.

{{ config.get(‘BRANDING\_ORG\_SITE\_NAME’) }}  should be the name of the nomad installation, not the website of the partner.

{{ config.get(‘BRANDING\_ORG\_NAME’) }} should be “The Arizona Democratic Party”

**Comment by jillh510** [comment]
<p>Effective and Last Updated: October 12, 2018</p>

<p>The site and services at {{ config.get('BRANDING\_ORG\_SITE\_NAME') }} are provided by {{ config.get('BRANDING\_ORG\_NAME') }} and by Ragtag, LLC on behalf of {{ config.get('BRANDING\_ORG\_NAME') }}, and we have a firm commitment to your privacy and Internet privacy in general. We are committed to protecting the privacy of our visitors and users while they interact with the content and services on this site ({{ config.get('BRANDING\_ORG\_SITE\_NAME') }} , the &ldquo;Site&rdquo;), and when they use the carpool matching services provided (the &ldquo;Services&rdquo;). This Privacy Policy applies to the {{ config.get('BRANDING\_ORG\_SITE\_NAME') }} Site only. It does not apply to other web sites to which we may link. We do gather certain types of information about our users, so we want you to understand what information we collect about you, how we collect it, how that information is used, and how you can control our disclosure of it. You agree that your use of the Site signifies your assent to this Privacy Policy. If you do not agree with this Privacy Policy, please do not use this Site.</p>

<p>1. Information Collected</p>

<p>We collect two types of information from you: 1) information that you voluntarily supply on this Site (e.g. through a voluntary registration process, or sign-up for eMail, or through signing up to participate in a carpool); and 2) information that may be derived through automated tracking mechanisms.</p>

<p>1.1. Voluntary Information for Services and Features</p>

<p>We collect personally identifiable information when you choose to use certain other features of the Site, including: a) when you sign up to host a carpool, b) when you sign up to participate in a carpool, c) consenting to receive eMail, d) participating in any interactive or social media as part of the Site, or e) any other personal information you share via comments and messages through the Services. When you choose to use these features, we may require you to provide your &ldquo;Contact Information&rdquo; in addition to other personal information that may be required to complete a transaction.</p>

<p>1.2. Cookies</p>

<p>Our site uses &ldquo;cookies&rdquo; and other web tracking technologies. Cookies enable us to serve secure pages to our users without asking them to sign in repeatedly. Most browsers allow you to control cookies, including whether or not to accept them and how to remove them. If a user&rsquo;s system is idle for a defined time, the cookie may expire, and if so, forcing the user to sign in again to continue their session. This prevents unauthorized access to the user&rsquo;s information while they are away from their computer.</p>

<p>You may set most browsers to notify you if you receive a cookie, or you may choose to block cookies with your browser, but please note that if you choose to erase or block your cookies, you may need to re-enter your original user ID and password to gain access to certain parts of the Site.</p>

<p>2. How We Use Your Information</p>

<p>{{ config.get('BRANDING\_ORG\_SITE\_NAME') }} uses your information for the purposes of providing you with the Site and the Services, and to let you know about events and information that may be of interest to you.</p>

<p>Please note that personally identifiable information is used only to provide you with a more enjoyable, convenient online experience and to help us identify and/or provide information that may be of interest to you. We use your personally identifiable information to support and enhance your use of the Site and its features, including without limitation: tracking eMail we send to you; and otherwise supporting your use of the Site.</p>

<p>We may permit certain trusted third parties to track usage, analyze data such as the source address that a page request is coming from, your IP address or domain name, the date and time of the page request, the referring Web site (if any) and other parameters in the URL. This is collected in order to better understand our Web site usage, and enhance the performance of services to maintain and operate the Site and certain features on the Site. We may use third parties to host the Site; operate various features available on the Site; send you eMail; analyze data; provide search results and links and assist in fulfilling your orders.</p>

<p>We may disclose Contact Information in special cases where we have reason to believe that disclosing this information is necessary to identify, contact or bring legal action against someone who may be violating our terms and conditions of use or may be causing injury or interference with our rights, property, our customers or anyone who could be harmed by such activities.</p>

<p>We are not liable or responsible for personally identifiable or other information you choose to submit on any publicly accessible area of the Site.</p>

<p>You will receive notice when your personally identifiable information might be provided to any third party for any reason other than as set forth in this Privacy Policy, and you will have an opportunity to request that we not share such information.</p>

<p>We use non-identifying and aggregate information to better design the Site and the Services and for business and administrative purposes. We may also use or share with third parties for any purpose aggregated data that contains no personally identifiable information.</p>

<p>3. How We Protect Your Information</p>

<p>We are committed to protecting the information we receive from you. We take appropriate security measures to protect your information against unauthorized access to or unauthorized alteration, disclosure or destruction of data. To prevent unauthorized access, maintain data accuracy, and ensure the correct use of information, we maintain appropriate physical, electronic, and managerial procedures to safeguard and secure the information and data stored on our system. While no computer system is ever completely secure, we believe the measures we have implemented reduce the likelihood of security problems to a level appropriate to the type of data involved.</p>

<p>4. Email Choice/Opt-out</p>

<p>If any user who receives an eMail from the Site and would prefer not to receive such communications in the future, he or she can do so by following the instructions in the eMail, where applicable. In addition, you may send an eMail to {{ config.get('BRANDING\_SUPPORT\_EMAIL') }}. We will make commercially reasonable efforts to implement your opt-out requests promptly, but you may still receive communications from us for up to ten business days as we process your request.</p>

<p>5. Disclaimer to Security</p>

<p>By consenting to the Privacy Policy, you consent that no data transmission over the Internet is completely secure. We cannot guarantee or warrant the security of any information you provide to us and you transmit such information to us at your own risk.</p>

<p>6. Notification of Changes</p>

<p>We reserve the right to change this Privacy Policy from time to time at our discretion. If at some point in the future, there is a change to our Privacy Policy, unless we obtain your express consent, such change will only apply to information collected after the revised Privacy Policy took effect. Your continued use of the Site indicates your assent to the Privacy Policy as posted.</p>

<p>7. Contact Information</p>

<p>If you have any questions or concerns regarding this Privacy Policy please contact:</p>

<p>team at {{ config.get('BRANDING\_SUPPORT\_EMAIL') }}</p>

<p>Terms of Use ------------</p>

<p>The following are the terms of use (TOU) you agree to abide by accessing {{ config.get('BRANDING\_ORG\_SITE\_NAME') }}. Last updated October 12, 2018.</p>

<p>LICENSE. If you are 18 or older, we grant you a limited, revocable, nonexclusive, nonassignable, nonsublicensable license to access {{ config.get('BRANDING\_ORG\_SITE\_NAME') }} in compliance with the TOU; unlicensed access is unauthorized. You agree not to license, distribute, make derivative works, display, sell, or &quot;frame&quot; content from {{ config.get('BRANDING\_ORG\_SITE\_NAME') }}, without prior permission from {{ config.get('BRANDING\_ORG\_NAME') }}. You grant {{ config.get('BRANDING\_ORG\_NAME') }} a perpetual, irrevocable, unlimited, worldwide, fully paid, sublicensable license to use, copy, perform, display, distribute, and make derivative works from content you post.</p>

<p>USE. You agree not to use or provide software (except for general purpose web browsers and email clients, or software expressly licensed by us) or services that interact or interoperate with {{ config.get('BRANDING\_ORG\_SITE\_NAME') }}, e.g. for downloading, uploading, posting, flagging, emailing, search, or mobile use. Robots, spiders, scripts, scrapers, crawlers, etc. are prohibited, as are misleading, unsolicited, unlawful, or spam postings/email. You agree not to collect users' personal and/or contact information (&quot;PI&quot;).</p>

<p>MODERATION. You agree we may moderate {{ config.get('BRANDING\_ORG\_SITE\_NAME') }} access and use in our sole discretion, e.g. by blocking (e.g. IP addresses), filtering, deletion, delay, omission, verification, or access/account/license termination. You agree (1) not to bypass this moderation, (2) we are not liable for moderating, not moderating, or representations as to moderating, and (3) nothing we say or do waives our right to moderate, or not.</p>

<p>DISCLAIMER. MANY JURISDICTIONS HAVE LAWS PROTECTING CONSUMERS AND OTHER CONTRACT PARTIES, LIMITING THEIR ABILITY TO WAIVE CERTAIN RIGHTS AND RESPONSIBILITIES. WE RESPECT SUCH LAWS; NOTHING HEREIN SHALL WAIVE RIGHTS OR RESPONSIBILITIES THAT CANNOT BE WAIVED.</p>

<p>To the extent permitted by law, (1) we make no promise as to {{ config.get('BRANDING\_ORG\_SITE\_NAME') }}, its completeness, accuracy, availability, timeliness, propriety, security or reliability; (2) your access and use are at your own risk, and {{ config.get('BRANDING\_ORG\_SITE\_NAME') }} is provided &quot;AS IS&quot; and &quot;AS AVAILABLE&quot;; (3) we are not liable for any harm resulting from (a) user content; (b) user conduct, e.g. illegal conduct; (c) your {{ config.get('BRANDING\_ORG\_SITE\_NAME') }} use; or (d) our representations; (4) WE AND OUR OFFICERS, DIRECTORS, EMPLOYEES (&quot;{{ config.get('BRANDING\_ORG\_NAME') }} ENTITIES&quot;), DISCLAIM ALL WARRANTIES &amp; CONDITIONS, EXPRESS OR IMPLIED, OF MERCHANTABILITY, FITNESS FOR PARTICULAR PURPOSE, OR NON-INFRINGEMENT; (5) {{ config.get('BRANDING\_ORG\_NAME') }} ENTITIES ARE NOT LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, OR ANY LOSS (E.G. OF PROFIT, REVENUE, DATA, OR GOODWILL); (6) IN NO EVENT SHALL OUR TOTAL LIABILITY EXCEED $100 OR WHAT YOU PAID US IN THE PAST YEAR.</p>

<p>CLAIMS. You agree (1) any claim, cause of action or dispute (&quot;Claim&quot;) arising out of or related to the TOU or your {{ config.get('BRANDING\_ORG\_SITE\_NAME') }} use is governed by California (&quot;CA&quot;) law regardless of your location or any conflict or choice of law principle; (2) Claims must be resolved exclusively by state or federal court in San Francisco, CA (except we may seek injunctive remedy anywhere); (3) to submit to personal jurisdiction of said courts; (4) any Claim must be filed by 1 year after it arose or be forever barred; (5) (except government agencies) to indemnify {{ config.get('BRANDING\_ORG\_NAME') }} for any damage, loss, and expense (e.g. legal fees) arising from claims related to your {{ config.get('BRANDING\_ORG\_SITE\_NAME') }} use; (6) you are liable for TOU breaches by affiliates (e.g. marketers) paid by you, directly or indirectly (e.g. through an affiliate network); and (7) to pay us for breaching or inducing others to breach the &quot;USE&quot; section, not as a penalty, but as a reasonable estimate of our damages (actual damages are often hard to calculate): $0.10 per server request, $10 per post, email, flag, or account created, $100 per item of PI collected, and $1000 per software distribution, capped at $25,000 per day.</p>

<p>MISC. Users complying with prior written licenses may access {{ config.get('BRANDING\_ORG\_SITE\_NAME') }} thereby until authorization is terminated. Otherwise, this is the exclusive and entire agreement between us. If a TOU term is unenforceable, other terms are unaffected. If TOU translations conflict with the English version, English controls. See Privacy Policy for how we collect, use and share data. If you feel content infringes your rights email {{ config.get('BRANDING\_ORG\_EMAIL') }}.</p>

<p>Organizer Liability Statement -----------------------------</p>

<p>By RSVPing to this event you agree and acknowledge that you have voluntarily requested to participate in the event at your own risk, you are aware of the risks or injuries that can occur when participating in the event, even where safety precautions are properly followed, and that you assume the risk of voluntarily participating in the event. You further agree to waive, release and discharge {{ config.get('BRANDING\_ORG\_NAME') }} and its successors, affiliates, subsidiaries, representatives, employees, agents and assigns from any and all claims, liabilities, obligations, demands and causes of action whatsoever, whether known or unknown, including, without limitation, claims for personal injury, wrongful death, property loss or damage, costs, charges, attorneys&rsquo; fees, court costs and other expenses of any kind (&ldquo;Claims&rdquo;) resulting from the negligence or other acts, howsoever caused, by any employee, agent, contractor or invitee of {{ config.get('BRANDING\_ORG\_NAME') }} arising out of or relating in any way to your participation in the event. You also agree to indemnify {{ config.get('BRANDING\_ORG\_NAME') }} and its directors, officers, agents and employees against any and all such Claims to the maximum extent permitted by law.</p>

<p>If you have any questions or concerns, please reach out to us at {{ config.get('BRANDING\_SUPPORT\_EMAIL') }}</p>

**Comment by tkell** [comment]
Seems like someone just needs to copy this into HTML?  If so, I will do this!
