### ISSUE TITLE
Users: Delete account

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#72]
Allow users to delete their account

On delete their information should be purged from the database

**Comment by iandees** [comment]
There is an account delete button on the user profile page.

**Comment by maiamcc** [comment]
Said button exists and does in fact delete the user's account. Still two to-do's associated with this ticket:
* [if user part of any carpools] notify drivers that this user has been removed from their carpool(s)
* [if user is a driver for any carpools] notify those carpool's passengers that carpools have been canceled

**Comment by engerm** [comment]
Users can now delete their account. Account is deleted and no longer shows up in userlist
