### ISSUE TITLE
Main page has placeholder contact email

### ISSUE THREAD

**Issue by TheUnlocked** [RagtagOpen/nomad#720]
The first paragraph under "Contact" on the main page currently says:

`For questions about carpools, canvasses, schedules, canvass locations, etc. please email the Ragtag team for help: from@example.com.`

**Comment by TheUnlocked** [comment]
It looks like the culprit is line 109 in https://github.com/RagtagOpen/nomad/blob/master/app/config.py

**Comment by jillh510** [comment]
This string is overridden using config vars in real deployments.
