### ISSUE TITLE
Create New York branding CSS

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/nomad#722]
Organization name: New York State Democratic Committee (“NYSDC”)
Logo: Attached
Headline 1: Carpool to canvass for New York Dems 
Headline 2: Find other volunteers near you who support Dems and join a carpool to flip a district!
Email: info@nydems.org
Privacy policy: default
URL for the organization for privacy policy: nydems.org

![nysdc logo 2 1](https://user-images.githubusercontent.com/2319837/46687418-b9b28580-cbaf-11e8-9aa2-19e48013862e.png)

Still needed: the signature for the emails , and, if you have it, a 1024x1024 version of the logo (used during Facebook login)

**Comment by dryan** [comment]
when this is done I can set the config variable for it

**Comment by jillh510** [comment]
Organization webpage: Nydems.org
Email signature: NY Dems
