### ISSUE TITLE
Drivers: set dates and times

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#73]
For drivers creating/editing a carpool, they should be able to set the dates and times

```
General time of day (early morning, morning, midday, afternoon, evening) and leave it to driver/passengers to coordinate offline

Departure time vs. arrival time? vs. days on the ground?
Show departure day and return day (are times important?)

```

**Comment by iandees** [comment]
This exists now with a date and hour. If we need to figure out how to do more fuzzy times please re-open, but know that it'll require a bit of thinking for how to handle that.
