### ISSUE TITLE
Drivers: Allow drivers to edit carpools

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#77]
Drivers should be able to edit their own carpools
* Driver should always be able to edit how many spots are available
* Edit anything they want until first passenger has requested
* Once a passenger has accepted, no more editing destination or departure/return times or location. Driver who wants to change things will need to cancel and and create a new carpool.

**Comment by dluetger** [comment]
Can the driver ever edit destination since the original was generated from choosing from the list?

**Comment by iandees** [comment]
I think we've decided to remove support for custom destinations, so a driver could select from a different destination, but not type a new address.

**Comment by dluetger** [comment]
Okay, then would it make sense to update the main "create" page to have a dropdown that defaults to the initial one they picked?

**Comment by dluetger** [comment]
Also, I added two new static pages but would like to add a delete button to each as well as somehow styling the "why the heck can't I edit these anymore" parts.

**Comment by iandees** [comment]
We only need to modify the templates, not the static pages. I think Michelle is using the static pages for experimenting with design.

**Comment by dluetger** [comment]
Roger.
