### ISSUE TITLE
Passengers: Searching for rides

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#81]
Allows passengers to search for volunteer opportunities.

Need to determine how they will search it:
- pickup location
- destination
- date
- special accommodations

**Comment by schloo** [comment]
Passengers will search by pickup location (zip code or city, zip) and results will be ordered by date

**Comment by iandees** [comment]
The search page exists and supports searching by pickup location only right now. I'm going to close this and encourage folks to open new tickets with more specific requests if what we have now isn't meeting expectations.
