### ISSUE TITLE
Passenger: be notified when carpool information has changed

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#84]
Be notified that a driver edited a carpool they applied to and_or were accepted to

**Comment by lperson** [comment]
Note that there is no way to edit a carpool in the app.  The app allows a carpool to be cancelled, and email is sent that happens.

I will edit the description.

**Comment by jillh510** [comment]
If there's no way to edit a carpool, can this issue be closed?

**Comment by engerm** [comment]
No, let's leave it open to track the feature request. 

If it's no longer a "priority" then we should remove the priority label. This issue can still track the original feature specification.

Note: 
Notifications being sent to riders after carpool changes is related to "Drivers: Allow drivers to edit carpools #77 "
