### ISSUE TITLE
Data: Nomad site should have web analytics (anonymous)

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#90]
Brady suggested something like Google Analytics. The web analytics must be anonymous

**Comment by kielni** [comment]
@bradyk is there a Ragtag Google Analytics account? I can add this if you send me the tracking code snippet.

**Comment by engerm** [comment]
I just created one using my email address. We can updated it later if needed:

```
<!-- Global Site Tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-107757413-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-107757413-1');
</script>

```

**Comment by iandees** [comment]
This is merged and the code is present on staging, but I think we should use separate tags for staging and prod. Can you make another tag for staging and post it here and I can configure it in Heroku.

**Comment by engerm** [comment]
@bradyk provided me with a new tracking tag.

Please remove the UA-107757413-1 tag.

Production should be: `UA-107712750-2`:

```
<!-- Global Site Tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-107712750-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-107712750-2');
</script>
```

I will add another for staging.

**Comment by engerm** [comment]
This is code for nomad-staging.ragtag.org:

```
<!-- Global Site Tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-107712750-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-107712750-3');
</script>
```

**Comment by engerm** [comment]
Task for me to check start are showing up in google docs

**Comment by iandees** [comment]
These are configured in both staging and production. The code is there, so this should be working in both environments.

**Comment by engerm** [comment]
Staging is getting stats but production is not.

Production template just went up today so it may take a day or two to start seeing these stats in google analytics.

**Comment by engerm** [comment]
Production real time is now showing numbers. 

All is good
