### ISSUE TITLE
Privacy: language needed for data sharing

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#92]
Language needs to be created for how:
- a passenger's data will be share with the campaign they will be volunteering at
- a driver's data will be share with the campaign they will be volunteering at
- a passenger's limited data will be share with the driver
- a driver's limited data will be share with their passengers

**Comment by schloo** [comment]
does this need to go in the privacy policy, or elsewhere? if the former, can be merged with #244

**Comment by schloo** [comment]
yes, this is covered in the privacy policy.
