### ISSUE TITLE
Feedback: nomad site should have a feedback/Contact Us option

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#93]
The nomad site should has a feedback/Contact Us feature where a user (driver, passenger, campaign) can contact Nomad volunteers to address any concerns or issues that user is having.

Example issues:
- delete me account and purge all data
- ride didn't show
- general usability feedback about nomad

**Comment by engerm** [comment]
this is related to #210 get Intercom working with nomad for support #210

**Comment by schloo** [comment]
I also added some space on it for the About/Home page... whoever figures out Intercom, is there a module we can plop there?

**Comment by iandees** [comment]
I'm going to close this as a dupe of #210.
