### ISSUE TITLE
Documentation: write steps for engineer to setup dev env

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#96]
Write steps for another engineer to use when setting up an development environment

**Comment by openbrian** [comment]
+1

**Comment by engerm** [comment]
@openbrian I believe @Rigdon updated the README.md with the setup instructions.

**Comment by Rigdon** [comment]
Yep. If there's anything missing or wrong let me know.

**Comment by openbrian** [comment]
Indeed, the env cars and docker compose worked well, with one exception.  I had to downgrade the minor number in the version number by one, due to an error about an incompatible file version.

**Comment by openbrian** [comment]
docker-compose.yml to 2.0.

**Comment by Rigdon** [comment]
@openbrian Sounds like the version of docker you have installed doesn't support 2.1? I'm on 17.06.0 and compose file version 2.1 has been out for a while.

**Comment by maiamcc** [comment]
Dev env setup was super smooth for me, can probs close this issue?

**Comment by iandees** [comment]
Yea, I think the docs have gotten much much better. Let's close this and open up new, more specific tickets if issues arise.
