### ISSUE TITLE
Unable to login/sign-in to test site 

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#98]
Site: https://ragtag-carpool.herokuapp.com/

Steps:

- Load page
- Click "Look for a ride"
- Click "Login"
- Click "Login with Facebook"
- enter FB creds

Actual Result:
Get FB error:
"App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions."

Expected Result:
- would get logged in and redirected back to the app

**Comment by iandees** [comment]
We can either start the process of getting the Facebook app approved or I can add your Facebook account as a tester if you'd like to get in immediately.

**Comment by engerm** [comment]
Is anyone familiar with getting an app approved by Facebook?

**Comment by iandees** [comment]
This is fixed.
